BEGIN;

-- === CATEGORIES ===
UPDATE community_categories SET name = 'Quadrinhos', description = 'Comunidades de quadrinhos e HQs' WHERE slug = 'comic-books';
UPDATE community_categories SET name = 'Filmes', description = 'Franquias de filmes' WHERE slug = 'movies';
UPDATE community_categories SET name = 'Animes', description = 'Anime e manga' WHERE slug = 'animes';
UPDATE community_categories SET name = 'Esportes', description = 'Para quem curte esportes' WHERE slug = 'sports';
UPDATE community_categories SET name = 'Jogos de Mesa', description = 'RPG de mesa e jogos de carta' WHERE slug = 'tabletop-games';
UPDATE community_categories SET name = 'Musica', description = 'Generos musicais' WHERE slug = 'music';
UPDATE community_categories SET name = 'Series de TV', description = 'Series e seriados' WHERE slug = 'tv-series';
UPDATE community_categories SET name = 'Geral', description = 'Interesse geral' WHERE slug = 'generic';

-- === TYPES (only translate where needed — proper nouns stay) ===
UPDATE community_types SET name = 'Futebol', description = 'O esporte mais popular do Brasil' WHERE slug = 'soccer';
UPDATE community_types SET name = 'Universo Marvel', description = 'Herois e viloes da Marvel' WHERE slug = 'marvel';
UPDATE community_types SET name = 'Universo DC', description = 'Herois e viloes da DC Comics' WHERE slug = 'dc';
UPDATE community_types SET name = 'Guerra nas Estrelas', description = 'A saga Star Wars' WHERE slug = 'star-wars';
UPDATE community_types SET name = 'Basquete', description = 'NBA e basquete mundial' WHERE slug = 'basketball';
UPDATE community_types SET name = 'Tenis', description = 'Tenis profissional' WHERE slug = 'tennis';
UPDATE community_types SET name = 'Luta', description = 'Boxe e artes marciais' WHERE slug = 'boxing';
UPDATE community_types SET name = 'Natacao', description = 'Natacao competitiva' WHERE slug = 'swimming';
UPDATE community_types SET name = 'Atletismo', description = 'Corrida e provas de campo' WHERE slug = 'athletics';
UPDATE community_types SET name = 'Ginastica', description = 'Ginastica artistica e ritmica' WHERE slug = 'gymnastics';
UPDATE community_types SET name = 'Golfe', description = 'Golfe profissional' WHERE slug = 'golf';
UPDATE community_types SET name = 'Senhor dos Aneis', description = 'A Terra-Media de Tolkien' WHERE slug = 'lotr';
UPDATE community_types SET name = 'De Volta pro Futuro', description = 'A trilogia classica' WHERE slug = 'back-to-future';
UPDATE community_types SET name = 'Velozes e Furiosos', description = 'Velocidade e familia' WHERE slug = 'fast-furious';
UPDATE community_types SET name = 'Piratas do Caribe', description = 'Jack Sparrow e seus piratas' WHERE slug = 'pirates-caribbean';
UPDATE community_types SET name = 'Missao Impossivel', description = 'Ethan Hunt em acao' WHERE slug = 'mission-impossible';
UPDATE community_types SET name = 'O Exterminador', description = 'Saga Terminator' WHERE slug = 'terminator';
UPDATE community_types SET name = 'Parque dos Dinossauros', description = 'O mundo de Jurassic Park' WHERE slug = 'jurassic-park';
UPDATE community_types SET name = 'A Casa do Dragao', description = 'Prequela de Game of Thrones' WHERE slug = 'house-of-dragon';
UPDATE community_types SET name = 'Chamado de Cthulhu', description = 'Horror cosmico de Lovecraft' WHERE slug = 'call-of-cthulhu';
UPDATE community_types SET name = 'Mascara do Vampiro', description = 'RPG de vampiros' WHERE slug = 'vampire-masquerade';
UPDATE community_types SET name = 'Classica', description = 'Musica classica' WHERE slug = 'classical';
UPDATE community_types SET name = 'Sertanejo', description = 'Musica sertaneja' WHERE slug = 'country';
UPDATE community_types SET name = 'Eletronica', description = 'Musica eletronica' WHERE slug = 'electronic';
UPDATE community_types SET name = 'Diarios do Vampiro', description = 'Serie sobrenatural' WHERE slug = 'vampire-diaries';
UPDATE community_types SET name = 'Ataque dos Titas', description = 'Shingeki no Kyojin' WHERE slug = 'attack-on-titan';
UPDATE community_types SET name = 'Cavaleiro da Lua', description = 'Moon Knight e herois' WHERE slug = 'heroes';
UPDATE community_types SET name = 'Predador', description = 'Saga Predator' WHERE slug = 'predator';

-- Types with good English names that are known in Brazil — keep original but add PT descriptions
UPDATE community_types SET description = 'O universo Dragon Ball' WHERE slug = 'dragon-ball';
UPDATE community_types SET description = 'O mundo magico de Hogwarts' WHERE slug = 'harry-potter';
UPDATE community_types SET description = 'A saga do Trono de Ferro' WHERE slug = 'game-of-thrones';
UPDATE community_types SET description = 'Rock classico e moderno' WHERE slug = 'rock';
UPDATE community_types SET description = 'Dungeons and Dragons - RPG' WHERE slug = 'dnd';
UPDATE community_types SET description = 'Magic: The Gathering - cartas' WHERE slug = 'mtg';
UPDATE community_types SET description = 'O universo ninja de Naruto' WHERE slug = 'naruto';
UPDATE community_types SET description = 'Coisas estranhas acontecem' WHERE slug = 'stranger-things';
UPDATE community_types SET description = 'Musica pop' WHERE slug = 'pop';
UPDATE community_types SET description = 'Walter White e o submundo' WHERE slug = 'breaking-bad';
UPDATE community_types SET description = 'As Tartarugas Ninja' WHERE slug = 'tmnt';
UPDATE community_types SET description = 'O mundo pirata de One Piece' WHERE slug = 'one-piece';
UPDATE community_types SET description = 'Pokemon - cartas colecionaveis' WHERE slug = 'pokemon-tcg';
UPDATE community_types SET description = 'Rap e hip hop' WHERE slug = 'hip-hop';
UPDATE community_types SET description = 'O bruxo Geralt de Rivia' WHERE slug = 'witcher';
UPDATE community_types SET description = 'Formula 1 e automobilismo' WHERE slug = 'formula-1';
UPDATE community_types SET description = 'Shinigamis e Hollows' WHERE slug = 'bleach';
UPDATE community_types SET description = 'O anti-heroi do inferno' WHERE slug = 'spawn';
UPDATE community_types SET description = 'Duelos de cartas' WHERE slug = 'yugioh';
UPDATE community_types SET description = 'O ultimo mestre do ar' WHERE slug = 'avatar';
UPDATE community_types SET description = 'Artes marciais mistas' WHERE slug = 'mma';
UPDATE community_types SET description = 'Super-herois sem limites' WHERE slug = 'the-boys';
UPDATE community_types SET description = 'Heavy metal e subgeneros' WHERE slug = 'metal';
UPDATE community_types SET description = 'Din Djarin e Baby Yoda' WHERE slug = 'mandalorian';
UPDATE community_types SET description = 'Batalhas epicas em miniatura' WHERE slug = 'warhammer';
UPDATE community_types SET description = 'Escolha a pilula vermelha' WHERE slug = 'matrix';
UPDATE community_types SET description = 'Jazz e improviso' WHERE slug = 'jazz';
UPDATE community_types SET description = 'O assassino implacavel' WHERE slug = 'john-wick';
UPDATE community_types SET description = 'Gon e seus amigos Hunters' WHERE slug = 'hunter-x-hunter';
UPDATE community_types SET description = 'Tommy Shelby e a gangue' WHERE slug = 'peaky-blinders';
UPDATE community_types SET description = 'Exploracao espacial RPG' WHERE slug = 'starfinder';
UPDATE community_types SET description = 'Corrida sombria no futuro' WHERE slug = 'shadowrun';
UPDATE community_types SET description = 'Boku no Hero Academia' WHERE slug = 'my-hero-academia';
UPDATE community_types SET description = 'A Federacao estelar' WHERE slug = 'star-trek';
UPDATE community_types SET description = 'O arqueologista aventureiro' WHERE slug = 'indiana-jones';
UPDATE community_types SET description = 'O caderno da morte' WHERE slug = 'death-note';
UPDATE community_types SET description = 'Alquimistas e transmutacao' WHERE slug = 'fullmetal-alchemist';
UPDATE community_types SET description = 'O jogo mortal coreano' WHERE slug = 'squid-game';
UPDATE community_types SET description = 'Mundo das fadas e magos' WHERE slug = 'fairy-tail';
UPDATE community_types SET description = 'Asta e os cavaleiros magicos' WHERE slug = 'black-clover';
UPDATE community_types SET description = 'Saitama e um soco so' WHERE slug = 'one-punch-man';
UPDATE community_types SET description = 'Feiticaria e maldições' WHERE slug = 'jujutsu-kaisen';
UPDATE community_types SET description = 'RPG de exploracao' WHERE slug = 'pathfinder';
UPDATE community_types SET description = 'Autobots vs Decepticons' WHERE slug = 'transformers';
UPDATE community_types SET description = 'Lobo adolescente' WHERE slug = 'teen-wolf';
UPDATE community_types SET description = 'Zumbis e sobrevivencia' WHERE slug = 'walking-dead';
UPDATE community_types SET description = 'Xenomorfos no espaco' WHERE slug = 'alien';
UPDATE community_types SET description = 'RPG virtual de espadas' WHERE slug = 'sword-art-online';
UPDATE community_types SET description = 'Tanjiro e os cacadores de demonios' WHERE slug = 'demon-slayer';

COMMIT;
