BEGIN;
UPDATE communities SET description = 'Cacadores de tesouros' WHERE slug = 'adventurers';
UPDATE communities SET description = 'Organizacao Akatsuki' WHERE slug = 'akatsuki';
UPDATE communities SET description = 'April, Casey e Splinter' WHERE slug = 'tmnt-allies';
UPDATE communities SET description = 'Rock moderno e alternativo' WHERE slug = 'alternative-rock';
UPDATE communities SET description = 'Vampiros rebeldes' WHERE slug = 'anarchs';
UPDATE communities SET description = 'Solo, salto e barras' WHERE slug = 'artistic-gymnastics';
UPDATE communities SET description = 'Membros do Continental' WHERE slug = 'assassins';
UPDATE communities SET description = 'Tenis masculino profissional' WHERE slug = 'atp-tour';
UPDATE communities SET description = 'Lutadores pela liberdade' WHERE slug = 'autobots';
UPDATE communities SET description = 'Os mais poderosos da Terra' WHERE slug = 'avengers';
UPDATE communities SET description = 'Protetores de Gotham' WHERE slug = 'bat-family';
UPDATE communities SET description = 'Jazz complexo e improvisado' WHERE slug = 'bebop';
UPDATE communities SET description = 'Outras promocoes de MMA' WHERE slug = 'bellator';
UPDATE communities SET description = 'Esquadrao do Asta' WHERE slug = 'black-bulls';
UPDATE communities SET description = 'Poder e morte' WHERE slug = 'black-mana';
UPDATE communities SET description = 'Faccao de Rhaenyra' WHERE slug = 'blacks';
UPDATE communities SET description = 'Conhecimento e controle' WHERE slug = 'blue-mana';
UPDATE communities SET description = 'Coletivo cibernetico' WHERE slug = 'borg';
UPDATE communities SET description = 'Futebol brasileiro' WHERE slug = 'brasileirao';
UPDATE communities SET description = 'Futebol alemao' WHERE slug = 'bundesliga';
UPDATE communities SET description = 'Sociedade vampirica' WHERE slug = 'camarilla';
UPDATE communities SET description = 'Vencedores de torneios' WHERE slug = 'pokemon-champions';
UPDATE communities SET description = 'Lendas da Formula 1' WHERE slug = 'f1-drivers';
UPDATE communities SET description = 'Deuses sombrios' WHERE slug = 'chaos';
UPDATE communities SET description = 'Sertanejo classico' WHERE slug = 'classic-country';
UPDATE communities SET description = 'Lendas dos anos 70 e 80' WHERE slug = 'classic-rock';
UPDATE communities SET description = 'Soldados espaciais' WHERE slug = 'colonial-marines';
UPDATE communities SET description = 'Organizacao secreta' WHERE slug = 'the-company';
UPDATE communities SET description = 'Grandes mestres' WHERE slug = 'composers';
UPDATE communities SET description = 'Equipes de corrida' WHERE slug = 'constructors';
UPDATE communities SET description = 'Entidades malignas' WHERE slug = 'cursed-spirits';
UPDATE communities SET description = 'Guildas do mal' WHERE slug = 'dark-guilds';
UPDATE communities SET description = 'Agencia antidrogas' WHERE slug = 'dea';
UPDATE communities SET description = 'Seguidores das trevas' WHERE slug = 'death-eaters';
UPDATE communities SET description = 'Conquistadores' WHERE slug = 'decepticons';
UPDATE communities SET description = 'Equipe dos Hashira' WHERE slug = 'demon-slayer-corps';
UPDATE communities SET description = 'Bestas pre-historicas' WHERE slug = 'dinosaurs';
UPDATE communities SET description = 'Jogadores de cartas' WHERE slug = 'duelists';
UPDATE communities SET description = 'Lendas de Nova York' WHERE slug = 'east-coast';
UPDATE communities SET description = 'Fantasia sombria' WHERE slug = 'eberron';
UPDATE communities SET description = 'Reinos elficos' WHERE slug = 'lotr-elves';
UPDATE communities SET description = 'Protetores imortais' WHERE slug = 'eternals';
UPDATE communities SET description = 'Elite europeia do basquete' WHERE slug = 'euroleague';
UPDATE communities SET description = 'Death metal e black metal' WHERE slug = 'extreme-metal';
UPDATE communities SET description = 'Terroristas' WHERE slug = 'eye-midnight-sun';
UPDATE communities SET description = 'Guilda principal' WHERE slug = 'fairy-tail-guild';
UPDATE communities SET description = 'Equipe do Dom' WHERE slug = 'ff-family';
UPDATE communities SET description = 'A primeira familia' WHERE slug = 'fantastic-four';
UPDATE communities SET description = 'Portadores do anel' WHERE slug = 'fellowship';
UPDATE communities SET description = 'Salto e lancamento' WHERE slug = 'field-events';
UPDATE communities SET description = 'Fogo e destruicao' WHERE slug = 'fire-nation' ;
UPDATE communities SET description = 'Monstros do lago' WHERE slug = 'loch-ness';
UPDATE communities SET description = 'Caos e diversao' WHERE slug = 'foot-clan';
UPDATE communities SET description = 'Novos talentos' WHERE slug = 'free-agents';
UPDATE communities SET description = 'Estilo livre e costas' WHERE slug = 'freestyle';
UPDATE communities SET description = 'Furia e velocidade' WHERE slug = 'furious-racers';
UPDATE communities SET description = 'Galaxia e cosmo' WHERE slug = 'galactic-empire';
UPDATE communities SET description = 'Guardias do universo' WHERE slug = 'green-lantern-corps';
UPDATE communities SET description = 'Crescimento e natureza' WHERE slug = 'green-mana';
UPDATE communities SET description = 'Protetores da galaxia' WHERE slug = 'guardians';
UPDATE communities SET description = 'Casa da coragem' WHERE slug = 'gryffindor';
UPDATE communities SET description = 'Exorcistas de Jujutsu' WHERE slug = 'jujutsu-sorcerers';
UPDATE communities SET description = 'Liga da Justica' WHERE slug = 'justice-league';
UPDATE communities SET description = 'Lideres do mundo ninja' WHERE slug = 'kage';
UPDATE communities SET description = 'Deuses e titulos' WHERE slug = 'legendary-trainers';
UPDATE communities SET description = 'Lendas americanas' WHERE slug = 'nba';
UPDATE communities SET description = 'Universitario americano' WHERE slug = 'ncaa-basketball';
UPDATE communities SET description = 'Guerreiros do Valhalla' WHERE slug = 'norse-mythology';
UPDATE communities SET description = 'Ordem dos Cavaleiros Jedi' WHERE slug = 'jedi-order';
UPDATE communities SET description = 'Piratas do Grand Line' WHERE slug = 'straw-hat-pirates';
UPDATE communities SET description = 'Marinha do Governo Mundial' WHERE slug = 'marines-op';
UPDATE communities SET description = 'Fogo e poder' WHERE slug = 'red-mana';
UPDATE communities SET description = 'Alianca Rebelde' WHERE slug = 'rebel-alliance';
UPDATE communities SET description = 'Lendas do rock classico' WHERE slug = 'rock-legends';
UPDATE communities SET description = 'Lendas do basquete' WHERE slug = 'nba-legends';
UPDATE communities SET description = 'Guerreiros Saiyajin' WHERE slug = 'z-fighters';
UPDATE communities SET description = 'Casa da lealdade' WHERE slug = 'hufflepuff';
UPDATE communities SET description = 'Jovens Titas' WHERE slug = 'teen-titans';
UPDATE communities SET description = 'Senhores Sith' WHERE slug = 'sith';
UPDATE communities SET description = 'Futebol italiano' WHERE slug = 'serie-a';
UPDATE communities SET description = 'Casa da sabedoria' WHERE slug = 'ravenclaw';
UPDATE communities SET description = 'Casa da ambicao' WHERE slug = 'slytherin';
UPDATE communities SET description = 'Cla Uchiha' WHERE slug = 'uchiha-clan';
UPDATE communities SET description = 'Mutantes heroicos' WHERE slug = 'x-men';
UPDATE communities SET description = 'Guerreiros Z de Dragon Ball' WHERE slug = 'z-fighters';
UPDATE communities SET description = 'Gangue de Birmingham' WHERE slug = 'shelbys';
UPDATE communities SET description = 'Hawkins e o Mundo Invertido' WHERE slug = 'hawkins-crew';
UPDATE communities SET description = 'Supers corrompidos' WHERE slug = 'the-seven';
UPDATE communities SET description = 'Herois da resistencia' WHERE slug = 'the-boys-team';
UPDATE communities SET description = 'Futebol espanhol' WHERE slug = 'la-liga';
UPDATE communities SET description = 'Futebol frances' WHERE slug = 'ligue-1';
UPDATE communities SET description = 'Futebol ingles' WHERE slug = 'premier-league';
UPDATE communities SET description = 'Hip hop da costa leste' WHERE slug = 'east-coast';
UPDATE communities SET description = 'Hip hop da costa oeste' WHERE slug = 'west-coast';
UPDATE communities SET description = 'Hip hop moderno' WHERE slug = 'new-school';
UPDATE communities SET description = 'Pop contemporaneo' WHERE slug = 'contemporary-pop';
UPDATE communities SET description = 'Icones do K-Pop' WHERE slug = 'k-pop';
UPDATE communities SET description = 'Lendas do pop' WHERE slug = 'pop-legends';
UPDATE communities SET description = 'Musica eletronica' WHERE slug = 'edm';
UPDATE communities SET description = 'Techno e house' WHERE slug = 'techno-house';
UPDATE communities SET description = 'Metal classico' WHERE slug = 'classic-metal';
UPDATE communities SET description = 'Thrash metal' WHERE slug = 'thrash-metal';
UPDATE communities SET description = 'Ordem Imperial' WHERE slug = 'imperium';
UPDATE communities SET description = 'Orcs e destruicao' WHERE slug = 'orks';
UPDATE communities SET description = 'Elfos espaciais' WHERE slug = 'eldar';
UPDATE communities SET description = 'Humanos do imperio' WHERE slug = 'mordor';
UPDATE communities SET description = 'Anoes guerreiros' WHERE slug = 'lotr-dwarves';
UPDATE communities SET description = 'Humanos da Terra-Media' WHERE slug = 'lotr-humans';
UPDATE communities SET description = 'Corridas de velocidade' WHERE slug = 'sprints';
UPDATE communities SET description = 'Corridas de longa distancia' WHERE slug = 'distance';
UPDATE communities SET description = 'Peito e borboleta' WHERE slug = 'breaststroke';
UPDATE communities SET description = 'Ritmica e acrobatica' WHERE slug = 'rhythmic';
UPDATE communities SET description = 'Tenis feminino profissional' WHERE slug = 'wta-tour';
UPDATE communities SET description = 'Grandes Slams historicos' WHERE slug = 'grand-slam-legends';
UPDATE communities SET description = 'Lendas do golfe' WHERE slug = 'pga-legends';
UPDATE communities SET description = 'Novos talentos do golfe' WHERE slug = 'pga-tour';
UPDATE communities SET description = 'Peso pesado do UFC' WHERE slug = 'ufc-heavyweight';
UPDATE communities SET description = 'Peso medio do UFC' WHERE slug = 'ufc-middleweight';
UPDATE communities SET description = 'Peso leve do UFC' WHERE slug = 'ufc-lightweight';
UPDATE communities SET description = 'Peso pena do UFC' WHERE slug = 'ufc-featherweight';
UPDATE communities SET description = 'Lendas do boxe' WHERE slug = 'boxing-legends';
UPDATE communities SET description = 'Campees atuais' WHERE slug = 'boxing-champions';
UPDATE communities SET description = 'Sobreviventes do jogo' WHERE slug = 'players-sg';
UPDATE communities SET description = 'Guardas e VIPs' WHERE slug = 'guards-sg';
UPDATE communities SET description = 'Demonios e Oni' WHERE slug = 'demons-ds';
UPDATE communities SET description = 'Cacadores de demonios da Lua' WHERE slug = 'upper-moons';
UPDATE communities SET description = 'Herois em treinamento' WHERE slug = 'ua-students';
UPDATE communities SET description = 'Viloes da Liga' WHERE slug = 'league-of-villains';
UPDATE communities SET description = 'Herois profissionais' WHERE slug = 'pro-heroes';
UPDATE communities SET description = 'Lendas do rap' WHERE slug = 'old-school';
UPDATE communities SET description = 'Reinos elementais' WHERE slug = 'forgotten-realms';
UPDATE communities SET description = 'Terras sombrias' WHERE slug = 'ravenloft';
UPDATE communities SET description = 'Exploracaoestelar' WHERE slug = 'starfleet';
UPDATE communities SET description = 'Viloes da Federacao' WHERE slug = 'villains-st';
UPDATE communities SET description = 'Aegon contra Rhaenyra' WHERE slug = 'greens';
COMMIT;
