UPDATE community_levels SET name = 'Iniciante', description = 'Seus primeiros passos' WHERE name = 'Delta' AND tier = 1;
UPDATE community_levels SET name = 'Aprendiz', description = 'Voce esta evoluindo' WHERE name = 'Gamma' AND tier = 2;
UPDATE community_levels SET name = 'Destaque', description = 'Seu esforco e reconhecido' WHERE name = 'Beta' AND tier = 3;
UPDATE community_levels SET name = 'Lider', description = 'Poucos chegam aqui' WHERE name = 'Alpha' AND tier = 4;
UPDATE community_levels SET name = 'Lenda', description = 'Legendario' WHERE name = 'Omega' AND tier = 5;
UPDATE community_levels SET name = 'Primeiro Ano', description = 'Novo estudante de magia' WHERE name = 'First Year';
UPDATE community_levels SET name = 'Estudante OWL', description = 'Preparando os exames' WHERE name = 'OWL Student';
UPDATE community_levels SET name = 'Estudante NEWT', description = 'Magia avancada' WHERE name = 'NEWT Student';
UPDATE community_levels SET description = 'Cacador das trevas' WHERE name = 'Auror';
UPDATE community_levels SET name = 'Lenda', description = 'Nome lembrado para sempre' WHERE name = 'Legend';
UPDATE community_levels SET name = 'Nivel 1', description = 'Primeiros passos' WHERE name LIKE 'Level 1%' AND tier = 1;
UPDATE community_levels SET name = 'Nivel 2', description = 'Evoluindo' WHERE name LIKE 'Level 5%' AND tier = 2;
UPDATE community_levels SET name = 'Nivel 3', description = 'Intermediario' WHERE name LIKE 'Level 11%' AND tier = 3;
UPDATE community_levels SET name = 'Nivel 4', description = 'Avancado' WHERE name LIKE 'Level 17%' AND tier = 4;
UPDATE community_levels SET name = 'Epico', description = 'Poder maximo' WHERE name = 'Epic';
UPDATE community_levels SET description = 'Nivel inicial' WHERE name = 'Rookie' AND tier = 1;
UPDATE community_levels SET description = 'Jogador regular' WHERE name = 'Regular' AND tier = 2;
UPDATE community_levels SET description = 'Jogador estrela' WHERE name = 'Star' AND tier = 3;
UPDATE community_levels SET description = 'Superstar do esporte' WHERE name = 'Superstar' AND tier = 4;
UPDATE community_levels SET description = 'Hall da fama' WHERE name = 'Hall of Fame' AND tier = 5;
UPDATE community_levels SET name = 'Novato' WHERE name = 'Rookie';
UPDATE community_levels SET name = 'Estrela' WHERE name = 'Star' AND tier = 3;
UPDATE community_levels SET name = 'Superestrela' WHERE name = 'Superstar' AND tier = 4;
UPDATE community_levels SET name = 'Hall da Fama' WHERE name = 'Hall of Fame' AND tier = 5;
UPDATE community_levels SET description = 'Nivel de entrada' WHERE description = 'Entry level';
UPDATE community_levels SET description = 'Poder medio' WHERE description = 'Medium power';
UPDATE community_levels SET description = 'Versatil' WHERE description = 'Versatile';
UPDATE community_levels SET description = 'Nivel superior' WHERE description = 'Top-tier';
UPDATE community_levels SET description = 'Escala da realidade' WHERE description = 'Reality-scale';
