BEGIN;
-- ============================================
-- TASK 1: Translate community descriptions to PT-BR
-- ============================================
UPDATE communities SET description = 'Caçadores de tesouros' WHERE slug = 'adventurers';
UPDATE communities SET description = 'Organização do amanhecer' WHERE slug = 'akatsuki';
UPDATE communities SET description = 'April Casey Splinter' WHERE slug = 'tmnt-allies';
UPDATE communities SET description = 'Rock moderno' WHERE slug = 'alternative-rock';
UPDATE communities SET description = 'Vampiros rebeldes' WHERE slug = 'anarchs';
UPDATE communities SET description = 'Solo e salto' WHERE slug = 'artistic-gymnastics';
UPDATE communities SET description = 'Membros continentais' WHERE slug = 'assassins';
UPDATE communities SET description = 'Tênis masculino' WHERE slug = 'atp-tour';
UPDATE communities SET description = 'Lutadores pela liberdade' WHERE slug = 'autobots';
UPDATE communities SET description = 'Os mais poderosos da Terra' WHERE slug = 'avengers';
UPDATE communities SET description = 'Protetores de Gotham' WHERE slug = 'bat-family';
UPDATE communities SET description = 'Jazz complexo' WHERE slug = 'bebop';
UPDATE communities SET description = 'Outras promoções' WHERE slug = 'bellator';
UPDATE communities SET description = 'Esquadrão do Asta' WHERE slug = 'black-bulls';
UPDATE communities SET description = 'Poder e morte' WHERE slug = 'black-mana';
UPDATE communities SET description = 'Facção de Rhaenyra' WHERE slug = 'blacks';
UPDATE communities SET description = 'Conhecimento e controle' WHERE slug = 'blue-mana';
UPDATE communities SET description = 'Coletivo cibernético' WHERE slug = 'borg';
UPDATE communities SET description = 'Futebol brasileiro' WHERE slug = 'brasileirao';
UPDATE communities SET description = 'Futebol alemão' WHERE slug = 'bundesliga';
UPDATE communities SET description = 'Sociedade vampírica' WHERE slug = 'camarilla';
UPDATE communities SET description = 'Vencedores de torneios' WHERE slug = 'pokemon-champions';
UPDATE communities SET description = 'Lendas da F1' WHERE slug = 'f1-drivers';
UPDATE communities SET description = 'Deuses sombrios' WHERE slug = 'chaos';
UPDATE communities SET description = 'Tradicional' WHERE slug = 'classic-country';
UPDATE communities SET description = 'Lendas dos anos 70 e 80' WHERE slug = 'classic-rock';
UPDATE communities SET description = 'Soldados espaciais' WHERE slug = 'colonial-marines';
UPDATE communities SET description = 'Organização secreta' WHERE slug = 'the-company';
UPDATE communities SET description = 'Mestres' WHERE slug = 'composers';
UPDATE communities SET description = 'Equipes de corrida' WHERE slug = 'constructors';
UPDATE communities SET description = 'Entidades malignas' WHERE slug = 'cursed-spirits';
UPDATE communities SET description = 'Guildas sombrias' WHERE slug = 'dark-guilds';
UPDATE communities SET description = 'Aplicação da lei' WHERE slug = 'dea';
UPDATE communities SET description = 'Seguidores das trevas' WHERE slug = 'death-eaters';
UPDATE communities SET description = 'Conquistadores' WHERE slug = 'decepticons';
UPDATE communities SET description = 'Equipe Hashira' WHERE slug = 'demon-slayer-corps';
UPDATE communities SET description = 'Feras pré-históricas' WHERE slug = 'dinosaurs';
UPDATE communities SET description = 'Jogadores de cartas' WHERE slug = 'duelists';
UPDATE communities SET description = 'Lendas de NY' WHERE slug = 'east-coast';
UPDATE communities SET description = 'Fantasia noir' WHERE slug = 'eberron';
UPDATE communities SET description = 'Reinos élficos' WHERE slug = 'lotr-elves';
UPDATE communities SET description = 'Protetores imortais' WHERE slug = 'eternals';
UPDATE communities SET description = 'Elite europeia' WHERE slug = 'euroleague';
UPDATE communities SET description = 'Death e black' WHERE slug = 'extreme-metal';
UPDATE communities SET description = 'Terroristas' WHERE slug = 'eye-midnight-sun';
UPDATE communities SET description = 'Guilda principal' WHERE slug = 'fairy-tail-guild';
UPDATE communities SET description = 'Equipe do Dom' WHERE slug = 'ff-family';
UPDATE communities SET description = 'Primeira família' WHERE slug = 'fantastic-four';
UPDATE communities SET description = 'Portadores do anel' WHERE slug = 'fellowship';
UPDATE communities SET description = 'Saltadores e lançadores' WHERE slug = 'field-events';
UPDATE communities SET description = 'Seguidores do Shredder' WHERE slug = 'foot-clan';
UPDATE communities SET description = 'Exército sombrio' WHERE slug = 'mordor';
UPDATE communities SET description = 'Aventuras em Faerun' WHERE slug = 'forgotten-realms';
UPDATE communities SET description = 'Conquistadores galácticos' WHERE slug = 'frieza-force';
UPDATE communities SET description = 'Ordem e força' WHERE slug = 'galactic-empire';
UPDATE communities SET description = 'Esquadrão de elite' WHERE slug = 'golden-dawn';
UPDATE communities SET description = 'Horrores cósmicos' WHERE slug = 'great-old-ones';
UPDATE communities SET description = 'Movidos pela vontade' WHERE slug = 'green-lantern-corps';
UPDATE communities SET description = 'Natureza e crescimento' WHERE slug = 'green-mana';
UPDATE communities SET description = 'Facção de Alicent' WHERE slug = 'greens';
UPDATE communities SET description = 'D&D clássico' WHERE slug = 'greyhawk';
UPDATE communities SET description = 'Bravos de coração' WHERE slug = 'gryffindor';
UPDATE communities SET description = 'Foras da lei cósmicos' WHERE slug = 'guardians-galaxy';
UPDATE communities SET description = 'Grupo principal' WHERE slug = 'hawkins-kids';
UPDATE communities SET description = 'Anjos guerreiros' WHERE slug = 'heaven-forces';
UPDATE communities SET description = 'Metal clássico' WHERE slug = 'heavy-metal';
UPDATE communities SET description = 'Campeões dos pesados' WHERE slug = 'heavyweight';
UPDATE communities SET description = 'Equipe do Walt' WHERE slug = 'heisenberg';
UPDATE communities SET description = 'Guerreiros do Spawn' WHERE slug = 'hellspawn';
UPDATE communities SET description = 'Heróis ranqueados' WHERE slug = 'hero-association';
UPDATE communities SET description = 'Humanos com poderes' WHERE slug = 'heroes-powered';
UPDATE communities SET description = 'Vontade do Fogo' WHERE slug = 'konoha';
UPDATE communities SET description = 'Senhores do crime' WHERE slug = 'high-table';
UPDATE communities SET description = 'Almas corrompidas' WHERE slug = 'hollows';
UPDATE communities SET description = 'Humanos artificiais' WHERE slug = 'homunculi';
UPDATE communities SET description = 'Música de clube' WHERE slug = 'house-music';
UPDATE communities SET description = 'Leais e justos' WHERE slug = 'hufflepuff';
UPDATE communities SET description = 'Caçadores licenciados' WHERE slug = 'hunters';
UPDATE communities SET description = 'Caçadores de lobisomens' WHERE slug = 'tw-hunters';
UPDATE communities SET description = 'Missões impossíveis' WHERE slug = 'imf-team';
UPDATE communities SET description = 'Remanescentes do império' WHERE slug = 'imperials';
UPDATE communities SET description = 'Forças humanas' WHERE slug = 'imperium';
UPDATE communities SET description = 'Buscadores da verdade' WHERE slug = 'investigators';
UPDATE communities SET description = 'Guardiões da paz' WHERE slug = 'jedi-order';
UPDATE communities SET description = 'Quebradores de maldição' WHERE slug = 'jujutsu-sorcerers';
UPDATE communities SET description = 'Os maiores do mundo' WHERE slug = 'justice-league';
UPDATE communities SET description = 'Buscadores de justiça' WHERE slug = 'kira-followers';
UPDATE communities SET description = 'Raça guerreira' WHERE slug = 'klingons';
UPDATE communities SET description = 'Futebol espanhol' WHERE slug = 'la-liga';
UPDATE communities SET description = 'Pagadores de dívidas' WHERE slug = 'lannisters';
UPDATE communities SET description = 'Assassinos virtuais' WHERE slug = 'laughing-coffin';
UPDATE communities SET description = 'Aliança do mal' WHERE slug = 'league-villains';
UPDATE communities SET description = 'Heróis de anime' WHERE slug = 'legendary-duelists';
UPDATE communities SET description = 'Três lendas' WHERE slug = 'sannin';
UPDATE communities SET description = 'Grandes do golfe' WHERE slug = 'golf-legends';
UPDATE communities SET description = 'Futebol francês' WHERE slug = 'ligue-1';
UPDATE communities SET description = 'Governantes de IA' WHERE slug = 'machines';
UPDATE communities SET description = 'Feiticeiros' WHERE slug = 'mages';
UPDATE communities SET description = 'Este é o caminho' WHERE slug = 'mandalorians';
UPDATE communities SET description = 'Caçadores de recompensa' WHERE slug = 'mando-clan';
UPDATE communities SET description = 'Governo mundial' WHERE slug = 'op-marines';
UPDATE communities SET description = 'Bando do Scott' WHERE slug = 'mccall-pack';
UPDATE communities SET description = 'Viajantes do tempo' WHERE slug = 'mcfly-family';
UPDATE communities SET description = 'Poderes corporativos' WHERE slug = 'megacorps';
UPDATE communities SET description = 'Country pop' WHERE slug = 'modern-country';
UPDATE communities SET description = 'Vilões' WHERE slug = 'monster-association';
UPDATE communities SET description = 'Personagens principais' WHERE slug = 'mystic-falls-gang';
UPDATE communities SET description = 'Nativos de Pandora' WHERE slug = 'navi';
UPDATE communities SET description = 'Forças reais' WHERE slug = 'navy';
UPDATE communities SET description = 'Forças inimigas' WHERE slug = 'ij-nazis';
UPDATE communities SET description = 'O melhor basquete' WHERE slug = 'nba';
UPDATE communities SET description = 'Basquete universitário' WHERE slug = 'ncaa-basketball';
UPDATE communities SET description = 'Império' WHERE slug = 'nilfgaard';
UPDATE communities SET description = 'As quatro tartarugas originais' WHERE slug = 'ninja-turtles';
UPDATE communities SET description = 'Medalhistas' WHERE slug = 'olympic-swimmers';
UPDATE communities SET description = 'Os primeiros vampiros' WHERE slug = 'originals';
UPDATE communities SET description = 'Guilda de aventureiros' WHERE slug = 'pathfinder-society';
UPDATE communities SET description = 'Família Shelby' WHERE slug = 'peaky-blinders-gang';
UPDATE communities SET description = 'Golfistas profissionais' WHERE slug = 'pga-tour';
UPDATE communities SET description = 'Ladrões' WHERE slug = 'phantom-troupe';
UPDATE communities SET description = 'Tripulação do Pérola Negra' WHERE slug = 'pirates';
UPDATE communities SET description = 'Participantes do jogo' WHERE slug = 'players';
UPDATE communities SET description = 'Superestrelas globais' WHERE slug = 'pop-icons';
UPDATE communities SET description = 'Reis libra por libra' WHERE slug = 'pound-for-pound';
UPDATE communities SET description = 'Futebol inglês' WHERE slug = 'premier-league';
UPDATE communities SET description = 'Heróis caçados' WHERE slug = 'prey';
UPDATE communities SET description = 'Heróis licenciados' WHERE slug = 'pro-heroes';
UPDATE communities SET description = 'Arqueiros espirituais' WHERE slug = 'quincies';
UPDATE communities SET description = 'Sabedoria sem medida' WHERE slug = 'ravenclaw';
UPDATE communities SET description = 'Horror gótico' WHERE slug = 'ravenloft';
UPDATE communities SET description = 'Corporação humana' WHERE slug = 'rda';
UPDATE communities SET description = 'A esperança vive' WHERE slug = 'rebel-alliance';
UPDATE communities SET description = 'Caos e paixão' WHERE slug = 'red-mana';
UPDATE communities SET description = 'Humanos livres' WHERE slug = 'resistance';
UPDATE communities SET description = 'Lutadores humanos' WHERE slug = 't-resistance';
UPDATE communities SET description = 'Fita e bola' WHERE slug = 'rhythmic-gymnastics';
UPDATE communities SET description = 'Gangues rivais' WHERE slug = 'pb-rivals';
UPDATE communities SET description = 'Mercenários' WHERE slug = 'runners';
UPDATE communities SET description = 'Vampiros monstruosos' WHERE slug = 'sabbat';
UPDATE communities SET description = 'Raça guerreira' WHERE slug = 'saiyan-warriors';
UPDATE communities SET description = 'Sobreviventes do jogo' WHERE slug = 'sao-survivors';
UPDATE communities SET description = 'Criadores do parque' WHERE slug = 'jp-scientists';
UPDATE communities SET description = 'Futebol italiano' WHERE slug = 'serie-a';
UPDATE communities SET description = 'Mestres do lado sombrio' WHERE slug = 'sith';
UPDATE communities SET description = 'Exército de máquinas' WHERE slug = 'skynet';
UPDATE communities SET description = 'Astutos e ambiciosos' WHERE slug = 'slytherin';
UPDATE communities SET description = 'Jazz moderno' WHERE slug = 'smooth-jazz';
UPDATE communities SET description = 'Gotei 13' WHERE slug = 'soul-reapers';
UPDATE communities SET description = 'Lançadores de teia' WHERE slug = 'spider-verse';
UPDATE communities SET description = 'Atletas de velocidade' WHERE slug = 'sprinters';
UPDATE communities SET description = 'Operadores do jogo' WHERE slug = 'staff';
UPDATE communities SET description = 'Exploradores espaciais' WHERE slug = 'starfinder-society';
UPDATE communities SET description = 'Heróis da Federação' WHERE slug = 'starfleet';
UPDATE communities SET description = 'O inverno está chegando' WHERE slug = 'starks';
UPDATE communities SET description = 'Alquimistas militares' WHERE slug = 'state-alchemists';
UPDATE communities SET description = 'Tripulação do Luffy' WHERE slug = 'straw-hats';
UPDATE communities SET description = 'Os piores heróis' WHERE slug = 'suicide-squad';
UPDATE communities SET description = 'Caçadores de titãs' WHERE slug = 'survey-corps';
UPDATE communities SET description = 'Grupo principal' WHERE slug = 'survivors';
UPDATE communities SET description = 'Fogo e sangue' WHERE slug = 'targaryens';
UPDATE communities SET description = 'Equipe do L' WHERE slug = 'task-force';
UPDATE communities SET description = 'Batidas underground' WHERE slug = 'techno';
UPDATE communities SET description = 'Jovens artistas' WHERE slug = 'teen-pop';
UPDATE communities SET description = 'Jovens heróis' WHERE slug = 'teen-titans';
UPDATE communities SET description = 'Caçadores de heróis' WHERE slug = 'the-boys-team';
UPDATE communities SET description = 'Heróis corruptos' WHERE slug = 'the-seven';
UPDATE communities SET description = 'Mestres de cartas' WHERE slug = 'pokemon-trainers';
UPDATE communities SET description = 'Demônios superiores' WHERE slug = 'twelve-moons';
UPDATE communities SET description = 'Academia de heróis' WHERE slug = 'ua-students';
UPDATE communities SET description = 'Portadores do Sharingan' WHERE slug = 'uchiha';
UPDATE communities SET description = 'Detentores de títulos' WHERE slug = 'ufc-champions';
UPDATE communities SET description = 'Campeões do Torneio do Poder' WHERE slug = 'universe-seven';
UPDATE communities SET description = 'Monstros' WHERE slug = 'upside-down';
UPDATE communities SET description = 'Ameaças globais' WHERE slug = 'mi-villains';
UPDATE communities SET description = 'Gangue do Biff' WHERE slug = 'bttf-villains';
UPDATE communities SET description = 'Antagonistas' WHERE slug = 'ff-villains';
UPDATE communities SET description = 'Ameaças cósmicas' WHERE slug = 'sf-villains';
UPDATE communities SET description = 'Grupos antagonistas' WHERE slug = 'wd-villains';
UPDATE communities SET description = 'Inimigos de campanha' WHERE slug = 'pf-villains';
UPDATE communities SET description = 'Artistas virtuosos' WHERE slug = 'virtuosos';
UPDATE communities SET description = 'Soldados de Marley' WHERE slug = 'warriors';
UPDATE communities SET description = 'Lendas de LA' WHERE slug = 'west-coast';
UPDATE communities SET description = 'Ordem e luz' WHERE slug = 'white-mana';
UPDATE communities SET description = 'Caçadores de monstros' WHERE slug = 'witchers';
UPDATE communities SET description = 'Lendas da velocidade' WHERE slug = 'world-record-holders';
UPDATE communities SET description = 'Tênis feminino' WHERE slug = 'wta-tour';
UPDATE communities SET description = 'Heróis mutantes' WHERE slug = 'x-men';
UPDATE communities SET description = 'Organismo perfeito' WHERE slug = 'xenomorphs';
UPDATE communities SET description = 'Raças alienígenas' WHERE slug = 'xenos';
UPDATE communities SET description = 'Raça caçadora' WHERE slug = 'yautja';
UPDATE communities SET description = 'Piratas imperadores' WHERE slug = 'yonko';
UPDATE communities SET description = 'Defensores da Terra' WHERE slug = 'z-fighters';
COMMIT;
-- ============================================
-- TASK 2: Translate character descriptions to PT-BR
-- Using bulk REPLACE for common English words/phrases
-- ============================================
BEGIN;
-- ===========================================
-- PHASE 1: Exact match translations for most common descriptions
-- ===========================================
UPDATE characters SET description = 'Membro da equipe' WHERE description = 'Team member';
UPDATE characters SET description = 'Membro dos Sobreviventes' WHERE description = 'Survivors member';
UPDATE characters SET description = 'Membro dos Vilões' WHERE description = 'WD Villains member';
UPDATE characters SET description = 'Membro dos Sete' WHERE description = 'The Seven member';
UPDATE characters SET description = 'Membro dos The Boys' WHERE description = 'The Boys Team member';
UPDATE characters SET description = 'Membro dos Autobots' WHERE description = 'Autobots member';
UPDATE characters SET description = 'Membro dos Decepticons' WHERE description = 'Decepticons member';
UPDATE characters SET description = 'Assassino' WHERE description = 'Assassin';
UPDATE characters SET description = 'Força-tarefa' WHERE description = 'Task force';
UPDATE characters SET description = 'Capitão' WHERE description = 'Captain';
UPDATE characters SET description = 'Mercenário' WHERE description = 'Mercenary';
UPDATE characters SET description = 'Tenente' WHERE description = 'Lieutenant';
UPDATE characters SET description = 'Comandante' WHERE description = 'Commander';
UPDATE characters SET description = 'Predador AVP' WHERE description = 'AVP predator';
UPDATE characters SET description = 'Líder de esquadrão' WHERE description = 'Squad leader';
UPDATE characters SET description = 'Hospedeiro do diabo' WHERE description = 'Devil host';
UPDATE characters SET description = 'Senhor do tráfico' WHERE description = 'Drug lord';
UPDATE characters SET description = 'Inteligência' WHERE description = 'Intelligence';
UPDATE characters SET description = 'Viajante do tempo' WHERE description = 'Time traveler';
UPDATE characters SET description = 'Bando de raptores' WHERE description = 'Raptor pack';
UPDATE characters SET description = 'Gangue do Biff' WHERE description = 'Biff gang';
UPDATE characters SET description = 'Soldado' WHERE description = 'Soldier';
UPDATE characters SET description = 'Pintura da morte' WHERE description = 'Death painting';
UPDATE characters SET description = 'Atirador de elite' WHERE description = 'Sniper';
UPDATE characters SET description = 'Guarda de elite' WHERE description = 'Elite guard';
UPDATE characters SET description = 'Artilheiro inteligente' WHERE description = 'Smart gunner';
UPDATE characters SET description = 'Espectador mascarado' WHERE description = 'Masked viewer';
UPDATE characters SET description = 'Criador' WHERE description = 'Creator';
UPDATE characters SET description = 'Magia de raio' WHERE description = 'Lightning magic';
UPDATE characters SET description = 'Coordenador regional' WHERE description = 'Regional coordinator';
UPDATE characters SET description = 'Comandante do Kaido' WHERE description = 'Kaido commander';
UPDATE characters SET description = 'Amigo leal' WHERE description = 'Loyal friend';
UPDATE characters SET description = 'Samurai' WHERE description = 'Samurai';
UPDATE characters SET description = 'Maior de todos' WHERE description = 'Greatest ever';
UPDATE characters SET description = 'Híbrido' WHERE description = 'Hybrid';
UPDATE characters SET description = 'Monstro devorador' WHERE description = 'Eating monster';
UPDATE characters SET description = 'Criação' WHERE description = 'Creation';
UPDATE characters SET description = 'Espadachim' WHERE description = 'Swordsman';
UPDATE characters SET description = 'Princesa' WHERE description = 'Princess';
UPDATE characters SET description = 'Doppelganger' WHERE description = 'Doppelganger';
UPDATE characters SET description = 'Distorcedor de realidade' WHERE description = 'Reality warper';
UPDATE characters SET description = 'Ex-capitão' WHERE description = 'Former Captain';
UPDATE characters SET description = 'Forma definitiva' WHERE description = 'Ultimate form';
UPDATE characters SET description = 'Lenda vocal' WHERE description = 'Voice legend';
UPDATE characters SET description = 'Hacker' WHERE description = 'Hacker';
UPDATE characters SET description = 'Estudante da academia' WHERE description = 'Academy student';
UPDATE characters SET description = 'Administrador' WHERE description = 'Administrator';
UPDATE characters SET description = 'Almirante' WHERE description = 'Admiral';
UPDATE characters SET description = 'Conselheiro' WHERE description = 'Advisor';
UPDATE characters SET description = 'Agente aliado' WHERE description = 'Agent ally';
UPDATE characters SET description = 'Aliado agente' WHERE description = 'Ally agent';
UPDATE characters SET description = 'Agente da agência' WHERE description = 'Agency agent';
UPDATE characters SET description = 'Alquimista' WHERE description = 'Alchemist';
UPDATE characters SET description = 'Invasor alienígena' WHERE description = 'Alien invader';
UPDATE characters SET description = 'Predador supremo' WHERE description = 'Apex predator';
UPDATE characters SET description = 'Arqueólogo' WHERE description = 'Archaeologist';
UPDATE characters SET description = 'Arcanjo' WHERE description = 'Archangel';
UPDATE characters SET description = 'Guarda-costas do arcebispo' WHERE description = 'Archbishop bodyguard';
UPDATE characters SET description = 'Funcionários armados' WHERE description = 'Armed staff';
UPDATE characters SET description = 'Irmão blindado' WHERE description = 'Armored brother';
UPDATE characters SET description = 'Herói blindado' WHERE description = 'Armored hero';
UPDATE characters SET description = 'Traficante de armas' WHERE description = 'Arms dealer';
UPDATE characters SET description = 'Bonecos do exército' WHERE description = 'Army dolls';
UPDATE characters SET description = 'Líder do exército' WHERE description = 'Army leader';
UPDATE characters SET description = 'Expressão artística' WHERE description = 'Artistic expression';
UPDATE characters SET description = 'Perfeição artística' WHERE description = 'Artistic perfection';
UPDATE characters SET description = 'Forma ascendida' WHERE description = 'Ascended form';
UPDATE characters SET description = 'Anjo de batalha' WHERE description = 'Battle angel';
UPDATE characters SET description = 'Guarda-costas' WHERE description = 'Bodyguard';
UPDATE characters SET description = 'Caçador de recompensas' WHERE description = 'Bounty legend';
UPDATE characters SET description = 'Rei menino' WHERE description = 'Boy King';
UPDATE characters SET description = 'O menino que sobreviveu' WHERE description = 'Boy Who Lived';
UPDATE characters SET description = 'Grifinória corajosa' WHERE description = 'Brave Gryffindor';
UPDATE characters SET description = 'A bruxa mais brilhante' WHERE description = 'Brightest witch';
UPDATE characters SET description = 'Canhão de guerra' WHERE description = 'Bronze Bomber';
UPDATE characters SET description = 'Mordomo - figura paterna' WHERE description = 'Butler - father figure';
UPDATE characters SET description = 'Câmera' WHERE description = 'Cameraman';
UPDATE characters SET description = 'Presidente' WHERE description = 'Chairman';
UPDATE characters SET description = 'Chanceler' WHERE description = 'Chancellor';
UPDATE characters SET description = 'Coronel' WHERE description = 'Colonel';
UPDATE characters SET description = 'Comando' WHERE description = 'Command';
UPDATE characters SET description = 'Comando' WHERE description = 'Commando';
UPDATE characters SET description = 'Líder de comando' WHERE description = 'Commando leader';
UPDATE characters SET description = 'Comentarista' WHERE description = 'Commentator';
UPDATE characters SET description = 'Comissário' WHERE description = 'Commissar';
UPDATE characters SET description = 'Herói comissário' WHERE description = 'Commissar hero';
UPDATE characters SET description = 'Comodoro' WHERE description = 'Commodore';
UPDATE characters SET description = 'Comunicações' WHERE description = 'Communications';
UPDATE characters SET description = 'Líder da empresa' WHERE description = 'Company leader';
UPDATE characters SET description = 'Agente da empresa' WHERE description = 'Company operative';
UPDATE characters SET description = 'Magia de bússola' WHERE description = 'Compass magic';
UPDATE characters SET description = 'Conjurador' WHERE description = 'Conjurer';
UPDATE characters SET description = 'Artista controverso' WHERE description = 'Controversial star';
UPDATE characters SET description = 'Cozinheiro' WHERE description = 'Cook';
UPDATE characters SET description = 'Drone corporativo' WHERE description = 'Corporate drone';
UPDATE characters SET description = 'Exército corporativo' WHERE description = 'Corporate army';
UPDATE characters SET description = 'Ser cósmico' WHERE description = 'Cosmic being';
UPDATE characters SET description = 'Entidades cósmicas' WHERE description = 'Cosmic entities';
UPDATE characters SET description = 'Entidade cósmica' WHERE description = 'Cosmic entity';
UPDATE characters SET description = 'Juiz cósmico' WHERE description = 'Cosmic judge';
UPDATE characters SET description = 'Poder cósmico' WHERE description = 'Cosmic power';
UPDATE characters SET description = 'Spawn cósmico' WHERE description = 'Cosmic spawn';
UPDATE characters SET description = 'Mago do conselho' WHERE description = 'Council mage';
UPDATE characters SET description = 'Mago da corte' WHERE description = 'Court mage';
UPDATE characters SET description = 'Rainha do country' WHERE description = 'Country queen';
UPDATE characters SET description = 'Membro da tripulação' WHERE description = 'Crew member';
UPDATE characters SET description = 'Advogado criminal' WHERE description = 'Criminal lawyer';
UPDATE characters SET description = 'Chefe do clã' WHERE description = 'Clan chief';
UPDATE characters SET description = 'Guerreiro do clã' WHERE description = 'Clan warrior';
UPDATE characters SET description = 'Alívio cômico' WHERE description = 'Comic relief';
UPDATE characters SET description = 'Pirata cômico' WHERE description = 'Comic pirate';
UPDATE characters SET description = 'Caçador por contrato' WHERE description = 'Contract hunter';
UPDATE characters SET description = 'Padre corrupto' WHERE description = 'Corrupt priest';
UPDATE characters SET description = 'Médico corrupto' WHERE description = 'Corrupt medic';
UPDATE characters SET description = 'Corrupção' WHERE description = 'Corruption';
UPDATE characters SET description = 'Primo gêmeo' WHERE description = 'Cousin twin';
UPDATE characters SET description = 'Palhaço demoníaco' WHERE description = 'Demon clown';
UPDATE characters SET description = 'Rei demônio' WHERE description = 'Demon King';
UPDATE characters SET description = 'Irmã demônio' WHERE description = 'Demon sister';
UPDATE characters SET description = 'Lobo demoníaco' WHERE description = 'Demon Wolf';
UPDATE characters SET description = 'Âncora defensiva' WHERE description = 'Defensive anchor';
UPDATE characters SET description = 'Mestre defensivo' WHERE description = 'Defensive master';
UPDATE characters SET description = 'Príncipe do diabo' WHERE description = 'Devil prince';
UPDATE characters SET description = 'Magia de dados' WHERE description = 'Dice magic';
UPDATE characters SET description = 'Diplomata' WHERE description = 'Diplomat';
UPDATE characters SET description = 'Forma digital' WHERE description = 'Digital form';
UPDATE characters SET description = 'Vontade divina' WHERE description = 'Divine will';
UPDATE characters SET description = 'Poder divino' WHERE description = 'Divine power';
UPDATE characters SET description = 'Ninja divino' WHERE description = 'Divine ninja';
UPDATE characters SET description = 'Doutor' WHERE description = 'Doctor';
UPDATE characters SET description = 'Monstros cães' WHERE description = 'Dog monsters';
UPDATE characters SET description = 'Mestre do dojo' WHERE description = 'Dojo master';
UPDATE characters SET description = 'Agente duplo' WHERE description = 'Double agent';
UPDATE characters SET description = 'Dupla estrela' WHERE description = 'Double Star';
UPDATE characters SET description = 'Duplo' WHERE description = 'Double';
UPDATE characters SET description = 'Mestre dragão' WHERE description = 'Dragon master';
UPDATE characters SET description = 'Rei dragão' WHERE description = 'Dragon King';
UPDATE characters SET description = 'Cavaleiro de dragão' WHERE description = 'Dragon rider';
UPDATE characters SET description = 'Rebelde dragão' WHERE description = 'Dragon rebel';
UPDATE characters SET description = 'Guardião do dragão' WHERE description = 'Dragon keeper';
UPDATE characters SET description = 'Sonhador' WHERE description = 'Dreamer';
UPDATE characters SET description = 'Rainha sonhadora' WHERE description = 'Dreamer queen';
UPDATE characters SET description = 'Eliminação eficiente' WHERE description = 'Efficient removal';
UPDATE characters SET description = 'Guerreiro de elite' WHERE description = 'Elite warrior';
UPDATE characters SET description = 'Hacker de elite' WHERE description = 'Elite hacker';
UPDATE characters SET description = 'Emissor' WHERE description = 'Emitter';
UPDATE characters SET description = 'Imperador' WHERE description = 'Emperor';
UPDATE characters SET description = 'Clone do imperador' WHERE description = 'Emperor clone';
UPDATE characters SET description = 'Absorvedor de energia' WHERE description = 'Energy absorber';
UPDATE characters SET description = 'Usuário de energia' WHERE description = 'Energy user';
UPDATE characters SET description = 'Engenheiro' WHERE description = 'Engineer';
UPDATE characters SET description = 'Variante do engenheiro' WHERE description = 'Engineer variant';
UPDATE characters SET description = 'Humano aprimorado' WHERE description = 'Enhanced human';
UPDATE characters SET description = 'Ninja aprimorado' WHERE description = 'Enhanced ninja';
UPDATE characters SET description = 'Aprimorador' WHERE description = 'Enhancer';
UPDATE characters SET description = 'Eterno' WHERE description = 'Eternal';
UPDATE characters SET description = 'Mago elemental' WHERE description = 'Elemental hero';
UPDATE characters SET description = 'Executor' WHERE description = 'Executioner';
UPDATE characters SET description = 'Explorador ativo' WHERE description = 'Active explorer';
UPDATE characters SET description = 'Explosão' WHERE description = 'Explosion';
UPDATE characters SET description = 'Pai enganado' WHERE description = 'Deceived father';
UPDATE characters SET description = 'Fanático devorador' WHERE description = 'Devourer fanatic';
UPDATE characters SET description = 'Destaque' WHERE description = 'Era defining';
UPDATE characters SET description = 'Caçador selvagem' WHERE description = 'Feral hunter';
UPDATE characters SET description = 'Agente de campo' WHERE description = 'Field agent';
UPDATE characters SET description = 'Comandante de campo' WHERE description = 'Field commander';
UPDATE characters SET description = 'Lutador' WHERE description = 'Fighter';
UPDATE characters SET description = 'Piloto de caça' WHERE description = 'Fighter pilot';
UPDATE characters SET description = 'Líder da família' WHERE description = 'Family leader';
UPDATE characters SET description = 'Demônio de fogo' WHERE description = 'Fire demon';
UPDATE characters SET description = 'Dragão de fogo' WHERE description = 'Fire dragon';
UPDATE characters SET description = 'Dragão de fogo' WHERE description = 'Fire Dragon';
UPDATE characters SET description = 'Magia de fogo' WHERE description = 'Fire magic';
UPDATE characters SET description = 'Espírito de fogo' WHERE description = 'Fire spirit';
UPDATE characters SET description = 'Primeiro imortal' WHERE description = 'First immortal';
UPDATE characters SET description = 'Primeira-dama' WHERE description = 'First Lady';
UPDATE characters SET description = 'Imediato' WHERE description = 'First mate';
UPDATE characters SET description = 'Primeiro oficial' WHERE description = 'First officer';
UPDATE characters SET description = 'Primeiro Ranger' WHERE description = 'First Ranger';
UPDATE characters SET description = 'Primeiro predador' WHERE description = 'First predator';
UPDATE characters SET description = 'Corredor de fundo' WHERE description = 'Fixer';
UPDATE characters SET description = 'Almirante da Frota' WHERE description = 'Fleet Admiral';
UPDATE characters SET description = 'Comandante da frota' WHERE description = 'Fleet commander';
UPDATE characters SET description = 'Monstros voadores' WHERE description = 'Flying monsters';
UPDATE characters SET description = 'Unidade voadora' WHERE description = 'Flying unit';
UPDATE characters SET description = 'Magia de comida' WHERE description = 'Food magic';
UPDATE characters SET description = 'Comandante do Foot' WHERE description = 'Foot commander';
UPDATE characters SET description = 'Líder do Foot' WHERE description = 'Foot leader';
UPDATE characters SET description = 'Um Proibido' WHERE description = 'Forbidden One';
UPDATE characters SET description = 'Força de criação' WHERE description = 'Creation force';
UPDATE characters SET description = 'Mestre da forja' WHERE description = 'Forge master';
UPDATE characters SET description = 'Ex-almirante' WHERE description = 'Former Admiral';
UPDATE characters SET description = 'Ex-almirante da Frota' WHERE description = 'Former Fleet Admiral';
UPDATE characters SET description = 'Ex-sombrio' WHERE description = 'Former dark';
UPDATE characters SET description = 'Ex-spawn' WHERE description = 'Former spawn';
UPDATE characters SET description = 'Fundador' WHERE description = 'Founder';
UPDATE characters SET description = 'Pirata feminina' WHERE description = 'Female pirate';
UPDATE characters SET description = 'Spawn feminino' WHERE description = 'Female spawn';
UPDATE characters SET description = 'Ninja raposa' WHERE description = 'Fox ninja';
UPDATE characters SET description = 'Fera livre' WHERE description = 'Free beast';
UPDATE characters SET description = 'Amizade' WHERE description = 'Friendship';
UPDATE characters SET description = 'Discursos de amizade' WHERE description = 'Friendship speeches';
UPDATE characters SET description = 'Forma completa' WHERE description = 'Fullmetal';
UPDATE characters SET description = 'Escudo galáctico' WHERE description = 'Galactic shield';
UPDATE characters SET description = 'Fantasma' WHERE description = 'Ghost';
UPDATE characters SET description = 'Lenda do golfe' WHERE description = 'Golf legend';
UPDATE characters SET description = 'Grande sacerdotisa' WHERE description = 'High priestess';
UPDATE characters SET description = 'Guarda' WHERE description = 'Guard';
UPDATE characters SET description = 'Guarda-costas' WHERE description = 'Bodyguard';
UPDATE characters SET description = 'Treinador de ginástica' WHERE description = 'Gymnastics coach';
UPDATE characters SET description = 'Rei caçador' WHERE description = 'Hunter King';
UPDATE characters SET description = 'Meia criativa' WHERE description = 'Creative mid';
UPDATE characters SET description = 'Lateral de ataque' WHERE description = 'Attack fullback';
UPDATE characters SET description = 'Pioneiro do drum' WHERE description = 'Drum pioneer';
UPDATE characters SET description = 'Inovador do drum' WHERE description = 'Drum innovator';
UPDATE characters SET description = 'Rebelde do clã' WHERE description = 'Corp rebel';
UPDATE characters SET description = 'Agente do EPF' WHERE description = 'EPF agent';
UPDATE characters SET description = 'Agente do FBI' WHERE description = 'FBI agent';
UPDATE characters SET description = 'Agente federal' WHERE description = 'Fed agent';
UPDATE characters SET description = 'Agente da CIA' WHERE description = 'CIA assassin';
UPDATE characters SET description = 'Diretor da CIA' WHERE description = 'CIA director';
UPDATE characters SET description = 'Agente DEA' WHERE description = 'DEA agent';
UPDATE characters SET description = 'Limpador de cena de crime' WHERE description = 'Crime scene cleaner';
UPDATE characters SET description = 'Senhor do crime - marca' WHERE description = 'Crime lord - marker';
UPDATE characters SET description = 'Chefe do cartel' WHERE description = 'Cartel boss';
UPDATE characters SET description = 'Psicopata do cartel' WHERE description = 'Cartel psycho';
UPDATE characters SET description = 'Babá' WHERE description = 'Babysitter';
UPDATE characters SET description = 'Traidor' WHERE description = 'Betrayer';
UPDATE characters SET description = 'Barão' WHERE description = 'Baron';
UPDATE characters SET description = 'Monstro celular' WHERE description = 'Cell monster';
UPDATE characters SET description = 'Caçadora Comanche' WHERE description = 'Comanche hunter';
UPDATE characters SET description = 'Unidade de combate' WHERE description = 'Combat unit';
UPDATE characters SET description = 'Mago de combate' WHERE description = 'Combat mage';
UPDATE characters SET description = 'Alienígena de combate' WHERE description = 'Combat alien';
UPDATE characters SET description = 'Portador de Dragonmark' WHERE description = 'Dragonmark bearer';
UPDATE characters SET description = 'Herói ranqueado' WHERE description = 'Ranked hero';
UPDATE characters SET description = 'Vingador - redimido' WHERE description = 'Avenger - redeemed';
UPDATE characters SET description = 'Irmã campeã' WHERE description = 'Champion sister';
UPDATE characters SET description = 'Líder coletivo' WHERE description = 'Collective leader';
UPDATE characters SET description = 'Pai barroco' WHERE description = 'Baroque father';
UPDATE characters SET description = 'Condutor pianista' WHERE description = 'Conductor pianist';
UPDATE characters SET description = 'Maestro de violoncelo' WHERE description = 'Cello master';
UPDATE characters SET description = 'Pássaro' WHERE description = 'Bird';
UPDATE characters SET description = 'Mutante pássaro' WHERE description = 'Bird mutant';
UPDATE characters SET description = 'Mutante anfíbio' WHERE description = 'Amphibian mutant';
UPDATE characters SET description = 'Aliena básica' WHERE description = 'Basic alien';
UPDATE characters SET description = 'Anjo básico' WHERE description = 'Basic angel';
UPDATE characters SET description = 'Ninja básico' WHERE description = 'Basic ninja';
UPDATE characters SET description = 'Staff básico' WHERE description = 'Basic staff';
UPDATE characters SET description = 'Unidade básica' WHERE description = 'Basic unit';
UPDATE characters SET description = 'Guerreiros antigos' WHERE description = 'Ancient warriors';
UPDATE characters SET description = 'Bruxa antiga' WHERE description = 'Ancient witch';
UPDATE characters SET description = 'Lobo antigo' WHERE description = 'Ancient wolf';
UPDATE characters SET description = 'Oficial androide' WHERE description = 'Android officer';
UPDATE characters SET description = 'Protetores anônimos' WHERE description = 'Anonymous protectors';
UPDATE characters SET description = 'Analista' WHERE description = 'Analyst';
UPDATE characters SET description = 'Sede ancestral de poder' WHERE description = 'Ancestral seat of power';
UPDATE characters SET description = 'Diletante' WHERE description = 'Dilettante';
UPDATE characters SET description = 'Arco da Encarnação' WHERE description = 'Arc of Embodiment';
UPDATE characters SET description = 'Prefeito ambicioso' WHERE description = 'Ambitious prefect';
UPDATE characters SET description = 'Maga arqueóloga' WHERE description = 'Archaeologist mage';
UPDATE characters SET description = 'Professor de arqueologia' WHERE description = 'Archaeology professor';
UPDATE characters SET description = 'Caçador de vampiros' WHERE description = 'Vampire hunter';
UPDATE characters SET description = 'Vampiro mau' WHERE description = 'Bad vampire';
UPDATE characters SET description = 'Patriarca maligno' WHERE description = 'Evil patriarch';
UPDATE characters SET description = 'Clone maligno' WHERE description = 'Evil clone';
UPDATE characters SET description = 'Telepata maligno' WHERE description = 'Evil telepath';
UPDATE characters SET description = 'Tartaruga maligna' WHERE description = 'Evil turtle';
UPDATE characters SET description = 'Pokémon da aura' WHERE description = 'Aura pokemon';
UPDATE characters SET description = 'Pokémon da evolução' WHERE description = 'Evolution pokemon';
UPDATE characters SET description = 'Rato elétrico' WHERE description = 'Electric mouse';
UPDATE characters SET description = 'Lobo nascido' WHERE description = 'Born werewolf';
UPDATE characters SET description = 'Lobo beta' WHERE description = 'Beta wolf';
UPDATE characters SET description = 'Decker elfo' WHERE description = 'Elf decker';
UPDATE characters SET description = 'Senhor elfo' WHERE description = 'Elf lord';
UPDATE characters SET description = 'Arqueiro élfico' WHERE description = 'Elven archer';
UPDATE characters SET description = 'Vidente' WHERE description = 'Farseer';
UPDATE characters SET description = 'Chefe do exílio' WHERE description = 'Exile boss';
UPDATE characters SET description = 'Guardas do exílio' WHERE description = 'Exile guards';
UPDATE characters SET description = 'Esposa do exílio' WHERE description = 'Exile wife';
UPDATE characters SET description = 'Estudante explosivo' WHERE description = 'Explosive student';
UPDATE characters SET description = 'Demônio de explosão' WHERE description = 'Explosion demon';
UPDATE characters SET description = 'Pirata de barba negra' WHERE description = 'Blackbeard pirate';
UPDATE characters SET description = 'Ferreiro' WHERE description = 'Blacksmith';
UPDATE characters SET description = 'Pirata ferreiro' WHERE description = 'Blacksmith pirate';
UPDATE characters SET description = 'Assassino cego' WHERE description = 'Blind assassin';
UPDATE characters SET description = 'Herói de resgate' WHERE description = 'Rescue hero';
UPDATE characters SET description = 'Cavaleiro negro' WHERE description = 'Black knight';
UPDATE characters SET description = 'Cavaleiro Negro' WHERE description = 'Black Knight';
UPDATE characters SET description = 'Fome sem fim' WHERE description = 'Endless hunger';
UPDATE characters SET description = 'Destruição sem fim' WHERE description = 'Endless Destruction';
UPDATE characters SET description = 'Artista marcial' WHERE description = 'Martial artist';
UPDATE characters SET description = 'Unidade de captura' WHERE description = 'Capture unit';
UPDATE characters SET description = 'Desempenho consistente' WHERE description = 'Consistent performers';
UPDATE characters SET description = 'Melhores da conferência' WHERE description = 'Best in conference';
UPDATE characters SET description = 'Desempenho consistente' WHERE description = 'Consistent performance';
UPDATE characters SET description = 'Rei Fada' WHERE description = 'Fairy King';
UPDATE characters SET description = 'Cavalaria de fé' WHERE description = 'Faith militant';
UPDATE characters SET description = 'Primarca caído' WHERE description = 'Fallen Primarch';
UPDATE characters SET description = 'Luz eterna' WHERE description = 'Forever light';
UPDATE characters SET description = 'Herói menor da flecha' WHERE description = 'Arrow hero - minor';
UPDATE characters SET description = 'Garras de adamantium' WHERE description = 'Adamantium claws';
UPDATE characters SET description = 'Organismo adaptativo' WHERE description = 'Adaptive organism';
UPDATE characters SET description = 'Rainha dos 400m' WHERE description = '400m queen';
UPDATE characters SET description = 'Rei dos 90' WHERE description = '90s king';
UPDATE characters SET description = 'Entidade abstrata' WHERE description = 'Abstract entity';
UPDATE characters SET description = 'Sombra do abismo' WHERE description = 'Abyss shadow';
UPDATE characters SET description = 'Programa de acesso' WHERE description = 'Access program';
UPDATE characters SET description = 'Estréia' WHERE description = 'Debut';
UPDATE characters SET description = 'Estrela da Ferrari' WHERE description = 'Ferrari star';
UPDATE characters SET description = 'Rainha do discus' WHERE description = 'Discus queen';
UPDATE characters SET description = 'Rainha da distância' WHERE description = 'Distance queen';
UPDATE characters SET description = 'Rei do nado peito' WHERE description = 'Breaststroke king';
UPDATE characters SET description = 'Rei da borboleta' WHERE description = 'Butterfly king';
UPDATE characters SET description = 'Maldição da terra' WHERE description = 'Earth curse';
UPDATE characters SET description = 'Maldição da floresta' WHERE description = 'Forest curse';
UPDATE characters SET description = 'Maldição cerebral' WHERE description = 'Brain curse';
UPDATE characters SET description = 'Soldado do droide' WHERE description = 'Droid soldier';
UPDATE characters SET description = 'Alienígena cerebral' WHERE description = 'Brain alien';
UPDATE characters SET description = 'Mentor do cartel' WHERE description = 'Cartel mentor';
UPDATE characters SET description = 'Fala amaldiçoada' WHERE description = 'Cursed speech';
UPDATE characters SET description = 'Ferramentas amaldiçoadas' WHERE description = 'Cursed tools';
UPDATE characters SET description = 'Cadáver amaldiçoado' WHERE description = 'Cursed corpse';
UPDATE characters SET description = 'Capitão amaldiçoado' WHERE description = 'Cursed captain';
UPDATE characters SET description = 'Marinheiro amaldiçoado' WHERE description = 'Cursed sailor';
UPDATE characters SET description = 'Eletrocinese' WHERE description = 'Electrokinesis';
UPDATE characters SET description = 'Eletrificação' WHERE description = 'Electrification';
UPDATE characters SET description = 'Soldado de Azlanti' WHERE description = 'Azlanti soldier';
UPDATE characters SET description = 'Jogador de cartas' WHERE description = 'Card player';
UPDATE characters SET description = 'Unidade de elite blindada negra' WHERE description = 'Elite black armor unit';
UPDATE characters SET description = 'Soldados de elite de infantaria' WHERE description = 'Elite foot soldiers';
UPDATE characters SET description = 'Infantaria de elite - Astapor' WHERE description = 'Elite infantry - Astapor';
UPDATE characters SET description = 'Aliado da necessidade' WHERE description = 'Ally of necessity';
UPDATE characters SET description = 'Soldados aliança terrestre' WHERE description = 'Alliance ground forces';
UPDATE characters SET description = 'Gorila cibernético' WHERE description = 'Cyber gorilla';
UPDATE characters SET description = 'Terrorista cibernético' WHERE description = 'Cyber terrorist';
UPDATE characters SET description = 'Supervilão IA' WHERE description = 'AI overlord';
UPDATE characters SET description = 'Vilão IA' WHERE description = 'AI villain';
UPDATE characters SET description = 'Armadura negra' WHERE description = 'Black armor';
UPDATE characters SET description = 'Metal negro' WHERE description = 'Black metal';
UPDATE characters SET description = 'Unidade blindada pessoal' WHERE description = 'Armored Personnel Unit';
UPDATE characters SET description = 'Magia anti-magia' WHERE description = 'Anti-magic';
UPDATE characters SET description = 'Bala' WHERE description = 'Bullet';
UPDATE characters SET description = 'Antagonista valentão' WHERE description = 'Bully antagonist';
UPDATE characters SET description = 'Filho do burgomestre' WHERE description = 'Burgomaster son';
UPDATE characters SET description = 'Mago de combate' WHERE description = 'Combat mage';
UPDATE characters SET description = 'Magia de cópia' WHERE description = 'Copy magic';
UPDATE characters SET description = 'Fogo e Sangue - 300 anos' WHERE description = 'Fire and Blood - 300 years';
UPDATE characters SET description = 'Primeiro assassino de xenomorfo' WHERE description = 'First xenomorph kill';
UPDATE characters SET description = 'Desculpas não aceitas' WHERE description = 'Apology not accepted';
UPDATE characters SET description = 'Começou' WHERE description = 'Beginning end';
UPDATE characters SET description = 'Disco pop' WHERE description = 'Disco pop';
UPDATE characters SET description = 'Herói ciborgue demoníaco' WHERE description = 'Demon Cyborg';
UPDATE characters SET description = 'Motorista de avatar' WHERE description = 'Avatar driver';
UPDATE characters SET description = 'Coronel avatar' WHERE description = 'Avatar colonel';
UPDATE characters SET description = 'Magia escura' WHERE description = 'Dark magic';
UPDATE characters SET description = 'Senhor sombrio' WHERE description = 'Dark lord';
UPDATE characters SET description = 'Senhor Sombrio' WHERE description = 'Dark Lord';
UPDATE characters SET description = 'Mensageiro sombrio' WHERE description = 'Dark messenger';
UPDATE characters SET description = 'Arauto sombrio' WHERE description = 'Dark herald';
UPDATE characters SET description = 'Industrial sombrio' WHERE description = 'Dark industrial';
UPDATE characters SET description = 'Estrela americana' WHERE description = 'American star';
UPDATE characters SET description = 'Veterano americano' WHERE description = 'American veteran';
UPDATE characters SET description = 'Prodígio americano' WHERE description = 'American prodigy';
UPDATE characters SET description = 'Mestre americano' WHERE description = 'American master';
UPDATE characters SET description = 'Chefe americano' WHERE description = 'American boss';
UPDATE characters SET description = 'Poder americano' WHERE description = 'American power';
UPDATE characters SET description = 'Equipe americana' WHERE description = 'American team';
UPDATE characters SET description = 'Lutador americano' WHERE description = 'American wrestler';
UPDATE characters SET description = 'Americano em ascensão' WHERE description = 'American rising';
UPDATE characters SET description = 'Americano estável' WHERE description = 'American steady';
UPDATE characters SET description = 'Violino americano' WHERE description = 'American violin';
UPDATE characters SET description = 'Salto americano' WHERE description = 'American vault';
UPDATE characters SET description = 'Velocidade americana' WHERE description = 'American flash';
UPDATE characters SET description = 'Lenda brasileira' WHERE description = 'Brazilian legend';
UPDATE characters SET description = 'Estrela brasileira' WHERE description = 'Brazilian star';
UPDATE characters SET description = 'Campeão brasileiro' WHERE description = 'Brazilian champ';
UPDATE characters SET description = 'Lutador brasileiro' WHERE description = 'Brazilian fighter';
UPDATE characters SET description = 'Rainha brasileira' WHERE description = 'Brazilian queen';
UPDATE characters SET description = 'Sprint brasileiro' WHERE description = 'Brazilian sprint';
UPDATE characters SET description = 'Lenda britânica' WHERE description = 'British legend';
UPDATE characters SET description = 'Estrela britânica' WHERE description = 'British star';
UPDATE characters SET description = 'Charme britânico' WHERE description = 'British charm';
UPDATE characters SET description = 'Lutador britânico' WHERE description = 'British fighter';
UPDATE characters SET description = 'Herança britânica' WHERE description = 'British heritage';
UPDATE characters SET description = 'Leão britânico' WHERE description = 'British lion';
UPDATE characters SET description = 'Poder britânico' WHERE description = 'British power';
UPDATE characters SET description = 'Precisão britânica' WHERE description = 'British precision';
UPDATE characters SET description = 'Corrida britânica' WHERE description = 'British racing';
UPDATE characters SET description = 'Voz britânica' WHERE description = 'British voice';
UPDATE characters SET description = 'Lenda canadense' WHERE description = 'Canadian legend';
UPDATE characters SET description = 'Prodígio canadense' WHERE description = 'Canadian prodigy';
UPDATE characters SET description = 'Cantor canadense' WHERE description = 'Canadian singer';
UPDATE characters SET description = 'Estrela canadense' WHERE description = 'Canadian star';
UPDATE characters SET description = 'Lenda holandesa' WHERE description = 'Dutch legend';
UPDATE characters SET description = 'Campeão holandês' WHERE description = 'Dutch champion';
UPDATE characters SET description = 'Estrela búlgara' WHERE description = 'Bulgarian star';
UPDATE characters SET description = 'Rainha belga' WHERE description = 'Belgian queen';
UPDATE characters SET description = 'Estrela belga' WHERE description = 'Belgian star';
UPDATE characters SET description = 'Estrela filipina' WHERE description = 'Filipino star';
UPDATE characters SET description = 'Estrela chinesa' WHERE description = 'Chinese star';
UPDATE characters SET description = 'Campeão australiano' WHERE description = 'Australian champ';
UPDATE characters SET description = 'Rainha australiana' WHERE description = 'Aussie queen';
UPDATE characters SET description = 'Talento australiano' WHERE description = 'Aussie talent';
UPDATE characters SET description = 'Tecnologia australiana' WHERE description = 'Aussie tech';
UPDATE characters SET description = 'Gênio austríaco' WHERE description = 'Austrian genius';
UPDATE characters SET description = 'Equipe austríaca' WHERE description = 'Austrian team';
UPDATE characters SET description = 'Chefe de Berlim' WHERE description = 'Berlin boss';
UPDATE characters SET description = 'Som de Berlim' WHERE description = 'Berlin sound';
UPDATE characters SET description = 'Rainha barbadiana' WHERE description = 'Barbadian queen';
UPDATE characters SET description = 'Poder bielorrusso' WHERE description = 'Belarusian power';
UPDATE characters SET description = 'Poder cubano' WHERE description = 'Cuban power';
UPDATE characters SET description = 'Raça dominicana' WHERE description = 'Dominican racer';
UPDATE characters SET description = 'Estrela dinamarquesa' WHERE description = 'Danish star';
UPDATE characters SET description = 'Fenômeno francês' WHERE description = 'French phenom';
UPDATE characters SET description = 'DJ francês' WHERE description = 'French DJ';
UPDATE characters SET description = 'Equipe francesa' WHERE description = 'French team';
UPDATE characters SET description = 'Impressionista francês' WHERE description = 'French impressionist';
UPDATE characters SET description = 'Campeonato francês' WHERE description = 'French championship';
UPDATE characters SET description = 'Líder rebelde' WHERE description = 'Rebel leader';
UPDATE characters SET description = 'Líder do esquadrão' WHERE description = 'Squad leader';
UPDATE characters SET description = 'Observador mascarado' WHERE description = 'Masked viewer';
UPDATE characters SET description = 'Clone maligno' WHERE description = 'Evil clone';
-- ===========================================
-- PHASE 2: Bulk word/phrase REPLACE translations
-- These translate common English words in descriptions
-- Order matters: longer phrases first, then single words
-- ===========================================
-- Multi-word phrases first (to avoid partial replacements)
UPDATE characters SET description = REPLACE(description, 'Team member', 'Membro da equipe') WHERE description LIKE '%Team member%';
UPDATE characters SET description = REPLACE(description, 'Squad leader', 'Líder de esquadrão') WHERE description LIKE '%Squad leader%';
UPDATE characters SET description = REPLACE(description, 'world champ', 'campeão mundial') WHERE description LIKE '%world champ%';
UPDATE characters SET description = REPLACE(description, 'world champion', 'campeão mundial') WHERE description LIKE '%world champion%';
UPDATE characters SET description = REPLACE(description, 'crime families', 'famílias do crime') WHERE description LIKE '%crime families%';
UPDATE characters SET description = REPLACE(description, 'crime lord', 'senhor do crime') WHERE description LIKE '%crime lord%';
UPDATE characters SET description = REPLACE(description, 'double champ', 'duplo campeão') WHERE description LIKE '%double champ%';
UPDATE characters SET description = REPLACE(description, 'teen prodigy', 'prodígio adolescente') WHERE description LIKE '%teen prodigy%';
UPDATE characters SET description = REPLACE(description, 'teen phenom', 'fenômeno adolescente') WHERE description LIKE '%teen phenom%';
UPDATE characters SET description = REPLACE(description, 'rising star', 'estrela em ascensão') WHERE description LIKE '%rising star%';
UPDATE characters SET description = REPLACE(description, 'power game', 'jogo de força') WHERE description LIKE '%power game%';
UPDATE characters SET description = REPLACE(description, 'power serve', 'saque potente') WHERE description LIKE '%power serve%';
UPDATE characters SET description = REPLACE(description, 'power striker', 'atacante potente') WHERE description LIKE '%power striker%';
UPDATE characters SET description = REPLACE(description, 'power strokes', 'golpes potentes') WHERE description LIKE '%power strokes%';
UPDATE characters SET description = REPLACE(description, 'big puncher', 'grande socador') WHERE description LIKE '%big puncher%';
UPDATE characters SET description = REPLACE(description, 'big game', 'grande jogo') WHERE description LIKE '%big game%';
UPDATE characters SET description = REPLACE(description, 'huge serve', 'saque enorme') WHERE description LIKE '%huge serve%';
UPDATE characters SET description = REPLACE(description, 'skilled boxer', 'boxeador habilidoso') WHERE description LIKE '%skilled boxer%';
UPDATE characters SET description = REPLACE(description, 'Olympic gold', 'ouro olímpico') WHERE description LIKE '%Olympic gold%';
UPDATE characters SET description = REPLACE(description, 'Olympic medals', 'medalhas olímpicas') WHERE description LIKE '%Olympic medals%';
UPDATE characters SET description = REPLACE(description, 'sprint king', 'rei da velocidade') WHERE description LIKE '%sprint king%';
UPDATE characters SET description = REPLACE(description, 'sprint power', 'força de velocidade') WHERE description LIKE '%sprint power%';
UPDATE characters SET description = REPLACE(description, 'patient player', 'jogador paciente') WHERE description LIKE '%patient player%';
UPDATE characters SET description = REPLACE(description, 'veteran winner', 'veterano vencedor') WHERE description LIKE '%veteran winner%';
UPDATE characters SET description = REPLACE(description, 'consistent', 'consistente') WHERE description LIKE '%consistent%';
UPDATE characters SET description = REPLACE(description, 'prospect developing', 'prospecto em desenvolvimento') WHERE description LIKE '%prospect developing%';
UPDATE characters SET description = REPLACE(description, 'flashy prospect', 'prospecto chamativo') WHERE description LIKE '%flashy prospect%';
UPDATE characters SET description = REPLACE(description, 'youngest star', 'estrela mais jovem') WHERE description LIKE '%youngest star%';
UPDATE characters SET description = REPLACE(description, 'young talent', 'jovem talento') WHERE description LIKE '%young talent%';
UPDATE characters SET description = REPLACE(description, 'young maestro', 'jovem maestro') WHERE description LIKE '%young maestro%';
UPDATE characters SET description = REPLACE(description, 'versatile leader', 'líder versátil') WHERE description LIKE '%versatile leader%';
UPDATE characters SET description = REPLACE(description, 'English striker', 'atacante inglês') WHERE description LIKE '%English striker%';
UPDATE characters SET description = REPLACE(description, 'German forward', 'atacante alemão') WHERE description LIKE '%German forward%';
UPDATE characters SET description = REPLACE(description, 'German gem', 'joia alemã') WHERE description LIKE '%German gem%';
UPDATE characters SET description = REPLACE(description, 'German winger', 'ponta alemão') WHERE description LIKE '%German winger%';
UPDATE characters SET description = REPLACE(description, 'French forward', 'atacante francês') WHERE description LIKE '%French forward%';
UPDATE characters SET description = REPLACE(description, 'Polish goal machine', 'máquina de gols polonesa') WHERE description LIKE '%Polish goal machine%';
UPDATE characters SET description = REPLACE(description, 'teenage warrior', 'guerreiro adolescente') WHERE description LIKE '%teenage warrior%';
UPDATE characters SET description = REPLACE(description, 'Norwegian cyborg', 'ciborgue norueguês') WHERE description LIKE '%Norwegian cyborg%';
UPDATE characters SET description = REPLACE(description, 'assist king', 'rei das assistências') WHERE description LIKE '%assist king%';
UPDATE characters SET description = REPLACE(description, 'sweeper keeper', 'goleiro líbero') WHERE description LIKE '%sweeper keeper%';
UPDATE characters SET description = REPLACE(description, 'captain creator', 'capitão criador') WHERE description LIKE '%captain creator%';
UPDATE characters SET description = REPLACE(description, 'midfield anchor', 'âncora do meio-campo') WHERE description LIKE '%midfield anchor%';
UPDATE characters SET description = REPLACE(description, 'free kick master', 'mestre de falta') WHERE description LIKE '%free kick master%';
UPDATE characters SET description = REPLACE(description, 'pace power', 'velocidade e força') WHERE description LIKE '%pace power%';
UPDATE characters SET description = REPLACE(description, 'ace pilot', 'piloto ás') WHERE description LIKE '%ace pilot%';
UPDATE characters SET description = REPLACE(description, 'bounty hunter', 'caçador de recompensas') WHERE description LIKE '%bounty hunter%';
UPDATE characters SET description = REPLACE(description, 'monster hunter', 'caçador de monstros') WHERE description LIKE '%monster hunter%';
UPDATE characters SET description = REPLACE(description, 'ancient weapon', 'arma antiga') WHERE description LIKE '%ancient weapon%';
UPDATE characters SET description = REPLACE(description, 'dark lord', 'senhor sombrio') WHERE description LIKE '%dark lord%';
UPDATE characters SET description = REPLACE(description, 'dark side', 'lado sombrio') WHERE description LIKE '%dark side%';
UPDATE characters SET description = REPLACE(description, 'fallen Jedi', 'Jedi caído') WHERE description LIKE '%fallen Jedi%';
UPDATE characters SET description = REPLACE(description, 'chosen one', 'escolhido') WHERE description LIKE '%chosen one%';
UPDATE characters SET description = REPLACE(description, 'Chosen One', 'Escolhido') WHERE description LIKE '%Chosen One%';
UPDATE characters SET description = REPLACE(description, 'strongest fighter', 'lutador mais forte') WHERE description LIKE '%strongest fighter%';
UPDATE characters SET description = REPLACE(description, 'strongest sword', 'espada mais forte') WHERE description LIKE '%strongest sword%';
UPDATE characters SET description = REPLACE(description, 'strongest being', 'ser mais forte') WHERE description LIKE '%strongest being%';
UPDATE characters SET description = REPLACE(description, 'mad scientist', 'cientista louco') WHERE description LIKE '%mad scientist%';
UPDATE characters SET description = REPLACE(description, 'ice dragon', 'dragão de gelo') WHERE description LIKE '%ice dragon%';
UPDATE characters SET description = REPLACE(description, 'wolf giant', 'lobo gigante') WHERE description LIKE '%wolf giant%';
UPDATE characters SET description = REPLACE(description, 'blind justice', 'justiça cega') WHERE description LIKE '%blind justice%';
UPDATE characters SET description = REPLACE(description, 'light speed', 'velocidade da luz') WHERE description LIKE '%light speed%';
UPDATE characters SET description = REPLACE(description, 'forest power', 'poder da floresta') WHERE description LIKE '%forest power%';
UPDATE characters SET description = REPLACE(description, 'time traveler', 'viajante do tempo') WHERE description LIKE '%time traveler%';
UPDATE characters SET description = REPLACE(description, 'space explorer', 'explorador espacial') WHERE description LIKE '%space explorer%';
UPDATE characters SET description = REPLACE(description, 'peace guardian', 'guardião da paz') WHERE description LIKE '%peace guardian%';
UPDATE characters SET description = REPLACE(description, 'death god', 'deus da morte') WHERE description LIKE '%death god%';
UPDATE characters SET description = REPLACE(description, 'death goddess', 'deusa da morte') WHERE description LIKE '%death goddess%';
UPDATE characters SET description = REPLACE(description, 'Death Star', 'Estrela da Morte') WHERE description LIKE '%Death Star%';
UPDATE characters SET description = REPLACE(description, 'Death Eater', 'Comensal da Morte') WHERE description LIKE '%Death Eater%';
UPDATE characters SET description = REPLACE(description, 'death machine', 'máquina de morte') WHERE description LIKE '%death machine%';
UPDATE characters SET description = REPLACE(description, 'Death Knight', 'Cavaleiro da Morte') WHERE description LIKE '%Death Knight%';
UPDATE characters SET description = REPLACE(description, 'Death Watch', 'Sentinela da Morte') WHERE description LIKE '%Death Watch%';
UPDATE characters SET description = REPLACE(description, 'god complex', 'complexo de deus') WHERE description LIKE '%god complex%';
UPDATE characters SET description = REPLACE(description, 'God of Shinobi', 'Deus dos Shinobi') WHERE description LIKE '%God of Shinobi%';
UPDATE characters SET description = REPLACE(description, 'God of Destruction', 'Deus da Destruição') WHERE description LIKE '%God of Destruction%';
UPDATE characters SET description = REPLACE(description, 'father figure', 'figura paterna') WHERE description LIKE '%father figure%';
UPDATE characters SET description = REPLACE(description, 'Naruto father figure', 'figura paterna do Naruto') WHERE description LIKE '%Naruto father figure%';
UPDATE characters SET description = REPLACE(description, 'twin brother', 'irmão gêmeo') WHERE description LIKE '%twin brother%';
UPDATE characters SET description = REPLACE(description, 'twin sister', 'irmã gêmea') WHERE description LIKE '%twin sister%';
UPDATE characters SET description = REPLACE(description, 'little sister', 'irmãzinha') WHERE description LIKE '%little sister%';
UPDATE characters SET description = REPLACE(description, 'big brother', 'irmão mais velho') WHERE description LIKE '%big brother%';
UPDATE characters SET description = REPLACE(description, 'evil empire', 'império maligno') WHERE description LIKE '%evil empire%';
UPDATE characters SET description = REPLACE(description, 'first victim', 'primeira vítima') WHERE description LIKE '%first victim%';
UPDATE characters SET description = REPLACE(description, 'gang member', 'membro da gangue') WHERE description LIKE '%gang member%';
UPDATE characters SET description = REPLACE(description, 'drug lord', 'senhor do tráfico') WHERE description LIKE '%drug lord%';
UPDATE characters SET description = REPLACE(description, 'vampire hunter', 'caçador de vampiros') WHERE description LIKE '%vampire hunter%';
UPDATE characters SET description = REPLACE(description, 'werewolf hunters', 'caçadores de lobisomens') WHERE description LIKE '%werewolf hunters%';
UPDATE characters SET description = REPLACE(description, 'First Vampire', 'Primeiro Vampiro') WHERE description LIKE '%First Vampire%';
UPDATE characters SET description = REPLACE(description, 'first vampire', 'primeiro vampiro') WHERE description LIKE '%first vampire%';
UPDATE characters SET description = REPLACE(description, 'team leader', 'líder de equipe') WHERE description LIKE '%team leader%';
UPDATE characters SET description = REPLACE(description, 'charge leader', 'líder de carga') WHERE description LIKE '%charge leader%';
UPDATE characters SET description = REPLACE(description, 'army leader', 'líder do exército') WHERE description LIKE '%army leader%';
UPDATE characters SET description = REPLACE(description, 'miracle worker', 'fazedor de milagres') WHERE description LIKE '%miracle worker%';
UPDATE characters SET description = REPLACE(description, 'child prodigy', 'criança prodígio') WHERE description LIKE '%child prodigy%';
UPDATE characters SET description = REPLACE(description, 'child of destiny', 'filho do destino') WHERE description LIKE '%child of destiny%';
UPDATE characters SET description = REPLACE(description, 'main character', 'personagem principal') WHERE description LIKE '%main character%';
UPDATE characters SET description = REPLACE(description, 'strongest', 'mais forte') WHERE description LIKE '%strongest%';
UPDATE characters SET description = REPLACE(description, 'fastest', 'mais rápido') WHERE description LIKE '%fastest%';
UPDATE characters SET description = REPLACE(description, 'deadliest', 'mais letal') WHERE description LIKE '%deadliest%';
UPDATE characters SET description = REPLACE(description, 'greatest', 'maior') WHERE description LIKE '%greatest%';
UPDATE characters SET description = REPLACE(description, 'youngest', 'mais jovem') WHERE description LIKE '%youngest%';
UPDATE characters SET description = REPLACE(description, 'eldest', 'mais velho') WHERE description LIKE '%eldest%';
UPDATE characters SET description = REPLACE(description, ' ruler', ' governante') WHERE description LIKE '% ruler%';
UPDATE characters SET description = REPLACE(description, ' protector', ' protetor') WHERE description LIKE '% protector%';
UPDATE characters SET description = REPLACE(description, ' warrior', ' guerreiro') WHERE description LIKE '% warrior%';
UPDATE characters SET description = REPLACE(description, ' soldier', ' soldado') WHERE description LIKE '% soldier%';
UPDATE characters SET description = REPLACE(description, ' hunter', ' caçador') WHERE description LIKE '% hunter%';
UPDATE characters SET description = REPLACE(description, ' killer', ' assassino') WHERE description LIKE '% killer%';
UPDATE characters SET description = REPLACE(description, ' leader', ' líder') WHERE description LIKE '% leader%';
UPDATE characters SET description = REPLACE(description, ' master', ' mestre') WHERE description LIKE '% master%';
UPDATE characters SET description = REPLACE(description, ' keeper', ' guardião') WHERE description LIKE '% keeper%';
UPDATE characters SET description = REPLACE(description, ' queen', ' rainha') WHERE description LIKE '% queen%';
UPDATE characters SET description = REPLACE(description, ' king', ' rei') WHERE description LIKE '% king%';
UPDATE characters SET description = REPLACE(description, ' legend', ' lenda') WHERE description LIKE '% legend%';
UPDATE characters SET description = REPLACE(description, ' champion', ' campeão') WHERE description LIKE '% champion%';
UPDATE characters SET description = REPLACE(description, ' villain', ' vilão') WHERE description LIKE '% villain%';
UPDATE characters SET description = REPLACE(description, ' traitor', ' traidor') WHERE description LIKE '% traitor%';
UPDATE characters SET description = REPLACE(description, ' healer', ' curandeiro') WHERE description LIKE '% healer%';
UPDATE characters SET description = REPLACE(description, ' creator', ' criador') WHERE description LIKE '% creator%';
UPDATE characters SET description = REPLACE(description, ' scientist', ' cientista') WHERE description LIKE '% scientist%';
UPDATE characters SET description = REPLACE(description, ' assassin', ' assassino') WHERE description LIKE '% assassin%';
UPDATE characters SET description = REPLACE(description, ' sorcerer', ' feiticeiro') WHERE description LIKE '% sorcerer%';
UPDATE characters SET description = REPLACE(description, ' wizard', ' mago') WHERE description LIKE '% wizard%';
UPDATE characters SET description = REPLACE(description, ' mercenary', ' mercenário') WHERE description LIKE '% mercenary%';
UPDATE characters SET description = REPLACE(description, ' pirate', ' pirata') WHERE description LIKE '% pirate%';
UPDATE characters SET description = REPLACE(description, ' prodigy', ' prodígio') WHERE description LIKE '% prodigy%';
UPDATE characters SET description = REPLACE(description, ' phenom', ' fenômeno') WHERE description LIKE '% phenom%';
UPDATE characters SET description = REPLACE(description, ' genius', ' gênio') WHERE description LIKE '% genius%';
UPDATE characters SET description = REPLACE(description, ' pioneer', ' pioneiro') WHERE description LIKE '% pioneer%';
UPDATE characters SET description = REPLACE(description, ' partner', ' parceiro') WHERE description LIKE '% partner%';
UPDATE characters SET description = REPLACE(description, ' brother', ' irmão') WHERE description LIKE '% brother%';
UPDATE characters SET description = REPLACE(description, ' sister', ' irmã') WHERE description LIKE '% sister%';
UPDATE characters SET description = REPLACE(description, ' father', ' pai') WHERE description LIKE '% father%';
UPDATE characters SET description = REPLACE(description, ' mother', ' mãe') WHERE description LIKE '% mother%';
UPDATE characters SET description = REPLACE(description, ' daughter', ' filha') WHERE description LIKE '% daughter%';
UPDATE characters SET description = REPLACE(description, ' son', ' filho') WHERE description LIKE '% son%';
UPDATE characters SET description = REPLACE(description, ' wife', ' esposa') WHERE description LIKE '% wife%';
UPDATE characters SET description = REPLACE(description, ' husband', ' marido') WHERE description LIKE '% husband%';
UPDATE characters SET description = REPLACE(description, ' friend', ' amigo') WHERE description LIKE '% friend%';
UPDATE characters SET description = REPLACE(description, ' ally', ' aliado') WHERE description LIKE '% ally%';
UPDATE characters SET description = REPLACE(description, ' enemy', ' inimigo') WHERE description LIKE '% enemy%';
UPDATE characters SET description = REPLACE(description, ' rival', ' rival') WHERE description LIKE '% rival%';
UPDATE characters SET description = REPLACE(description, ' member', ' membro') WHERE description LIKE '% member%';
UPDATE characters SET description = REPLACE(description, ' captain', ' capitão') WHERE description LIKE '% captain%';
UPDATE characters SET description = REPLACE(description, ' commander', ' comandante') WHERE description LIKE '% commander%';
UPDATE characters SET description = REPLACE(description, ' lieutenant', ' tenente') WHERE description LIKE '% lieutenant%';
UPDATE characters SET description = REPLACE(description, ' admiral', ' almirante') WHERE description LIKE '% admiral%';
UPDATE characters SET description = REPLACE(description, ' knight', ' cavaleiro') WHERE description LIKE '% knight%';
UPDATE characters SET description = REPLACE(description, ' prince', ' príncipe') WHERE description LIKE '% prince%';
UPDATE characters SET description = REPLACE(description, ' princess', ' princesa') WHERE description LIKE '% princess%';
UPDATE characters SET description = REPLACE(description, ' emperor', ' imperador') WHERE description LIKE '% emperor%';
UPDATE characters SET description = REPLACE(description, ' teacher', ' professor') WHERE description LIKE '% teacher%';
UPDATE characters SET description = REPLACE(description, ' student', ' estudante') WHERE description LIKE '% student%';
UPDATE characters SET description = REPLACE(description, ' monster', ' monstro') WHERE description LIKE '% monster%';
UPDATE characters SET description = REPLACE(description, ' demon', ' demônio') WHERE description LIKE '% demon%';
UPDATE characters SET description = REPLACE(description, ' dragon', ' dragão') WHERE description LIKE '% dragon%';
UPDATE characters SET description = REPLACE(description, ' vampire', ' vampiro') WHERE description LIKE '% vampire%';
UPDATE characters SET description = REPLACE(description, ' werewolf', ' lobisomem') WHERE description LIKE '% werewolf%';
UPDATE characters SET description = REPLACE(description, ' ghost', ' fantasma') WHERE description LIKE '% ghost%';
UPDATE characters SET description = REPLACE(description, ' witch', ' bruxa') WHERE description LIKE '% witch%';
UPDATE characters SET description = REPLACE(description, ' dwarf', ' anão') WHERE description LIKE '% dwarf%';
UPDATE characters SET description = REPLACE(description, ' giant', ' gigante') WHERE description LIKE '% giant%';
UPDATE characters SET description = REPLACE(description, ' immortal', ' imortal') WHERE description LIKE '% immortal%';
UPDATE characters SET description = REPLACE(description, ' ancient', ' antigo') WHERE description LIKE '% ancient%';
UPDATE characters SET description = REPLACE(description, ' loyal', ' leal') WHERE description LIKE '% loyal%';
UPDATE characters SET description = REPLACE(description, ' brave', ' corajoso') WHERE description LIKE '% brave%';
UPDATE characters SET description = REPLACE(description, ' powerful', ' poderoso') WHERE description LIKE '% powerful%';
UPDATE characters SET description = REPLACE(description, ' corrupt', ' corrupto') WHERE description LIKE '% corrupt%';
UPDATE characters SET description = REPLACE(description, ' cursed', ' amaldiçoado') WHERE description LIKE '% cursed%';
UPDATE characters SET description = REPLACE(description, ' dangerous', ' perigoso') WHERE description LIKE '% dangerous%';
UPDATE characters SET description = REPLACE(description, ' fallen', ' caído') WHERE description LIKE '% fallen%';
UPDATE characters SET description = REPLACE(description, ' survivor', ' sobrevivente') WHERE description LIKE '% survivor%';
UPDATE characters SET description = REPLACE(description, ' clone', ' clone') WHERE description LIKE '% clone%';
UPDATE characters SET description = REPLACE(description, ' redeemed', ' redimido') WHERE description LIKE '% redeemed%';
UPDATE characters SET description = REPLACE(description, ' reformed', ' reformado') WHERE description LIKE '% reformed%';
UPDATE characters SET description = REPLACE(description, ' betrayed', ' traído') WHERE description LIKE '% betrayed%';
UPDATE characters SET description = REPLACE(description, ' died', ' morreu') WHERE description LIKE '% died%';
UPDATE characters SET description = REPLACE(description, ' killed', ' morto') WHERE description LIKE '% killed%';
UPDATE characters SET description = REPLACE(description, ' escaped', ' escapou') WHERE description LIKE '% escaped%';
UPDATE characters SET description = REPLACE(description, ' missing', ' desaparecido') WHERE description LIKE '% missing%';
UPDATE characters SET description = REPLACE(description, ' exiled', ' exilado') WHERE description LIKE '% exiled%';
UPDATE characters SET description = REPLACE(description, ' blind', ' cego') WHERE description LIKE '% blind%';
UPDATE characters SET description = REPLACE(description, ' deaf', ' surdo') WHERE description LIKE '% deaf%';
UPDATE characters SET description = REPLACE(description, ' old', ' velho') WHERE description LIKE '% old%';
UPDATE characters SET description = REPLACE(description, ' young', ' jovem') WHERE description LIKE '% young%';
UPDATE characters SET description = REPLACE(description, ' dark', ' sombrio') WHERE description LIKE '% dark%';
UPDATE characters SET description = REPLACE(description, ' evil', ' maligno') WHERE description LIKE '% evil%';
UPDATE characters SET description = REPLACE(description, ' good', ' bom') WHERE description LIKE '% good%';
UPDATE characters SET description = REPLACE(description, ' holy', ' sagrado') WHERE description LIKE '% holy%';
UPDATE characters SET description = REPLACE(description, ' cursed', ' amaldiçoado') WHERE description LIKE '% cursed%';
UPDATE characters SET description = REPLACE(description, ' magic', ' magia') WHERE description LIKE '% magic%';
UPDATE characters SET description = REPLACE(description, ' hero', ' herói') WHERE description LIKE '% hero%';
UPDATE characters SET description = REPLACE(description, ' thief', ' ladrão') WHERE description LIKE '% thief%';
-- Starting words (capitalized)
UPDATE characters SET description = REPLACE(description, 'Warrior ', 'Guerreiro ') WHERE description LIKE 'Warrior %';
UPDATE characters SET description = REPLACE(description, 'Ancient ', 'Antigo ') WHERE description LIKE 'Ancient %';
UPDATE characters SET description = REPLACE(description, 'Dark ', 'Sombrio ') WHERE description LIKE 'Dark %';
UPDATE characters SET description = REPLACE(description, 'Evil ', 'Maligno ') WHERE description LIKE 'Evil %';
UPDATE characters SET description = REPLACE(description, 'Holy ', 'Sagrado ') WHERE description LIKE 'Holy %';
UPDATE characters SET description = REPLACE(description, 'Young ', 'Jovem ') WHERE description LIKE 'Young %';
UPDATE characters SET description = REPLACE(description, 'Old ', 'Velho ') WHERE description LIKE 'Old %';
UPDATE characters SET description = REPLACE(description, 'Elite ', 'Elite ') WHERE description LIKE 'Elite %';
UPDATE characters SET description = REPLACE(description, 'Loyal ', 'Leal ') WHERE description LIKE 'Loyal %';
UPDATE characters SET description = REPLACE(description, 'Brave ', 'Corajoso ') WHERE description LIKE 'Brave %';
UPDATE characters SET description = REPLACE(description, 'Powerful ', 'Poderoso ') WHERE description LIKE 'Powerful %';
UPDATE characters SET description = REPLACE(description, 'Former ', 'Ex-') WHERE description LIKE 'Former %';
UPDATE characters SET description = REPLACE(description, 'Secret ', 'Secreto ') WHERE description LIKE 'Secret %';
UPDATE characters SET description = REPLACE(description, 'Super ', 'Super ') WHERE description LIKE 'Super %';
UPDATE characters SET description = REPLACE(description, 'Cosmic ', 'Cósmico ') WHERE description LIKE 'Cosmic %';
UPDATE characters SET description = REPLACE(description, 'Magic ', 'Magia ') WHERE description LIKE 'Magic %';
UPDATE characters SET description = REPLACE(description, 'Flying ', 'Voador ') WHERE description LIKE 'Flying %';
UPDATE characters SET description = REPLACE(description, 'Blind ', 'Cego ') WHERE description LIKE 'Blind %';
UPDATE characters SET description = REPLACE(description, 'Corrupt ', 'Corrupto ') WHERE description LIKE 'Corrupt %';
UPDATE characters SET description = REPLACE(description, 'Cursed ', 'Amaldiçoado ') WHERE description LIKE 'Cursed %';
UPDATE characters SET description = REPLACE(description, 'Escaped ', 'Escapou ') WHERE description LIKE 'Escaped %';
UPDATE characters SET description = REPLACE(description, 'Fallen ', 'Caído ') WHERE description LIKE 'Fallen %';
UPDATE characters SET description = REPLACE(description, 'Fire ', 'Fogo ') WHERE description LIKE 'Fire %';
UPDATE characters SET description = REPLACE(description, 'Female ', 'Feminino ') WHERE description LIKE 'Female %';
UPDATE characters SET description = REPLACE(description, 'Immortal ', 'Imortal ') WHERE description LIKE 'Immortal %';
UPDATE characters SET description = REPLACE(description, 'Famous ', 'Famoso ') WHERE description LIKE 'Famous %';
UPDATE characters SET description = REPLACE(description, 'Fastest ', 'Mais rápido ') WHERE description LIKE 'Fastest %';
-- Common connector words
UPDATE characters SET description = REPLACE(description, ' turned ', ' tornou-se ') WHERE description LIKE '% turned %';
UPDATE characters SET description = REPLACE(description, ' and ', ' e ') WHERE description LIKE '% and %';
UPDATE characters SET description = REPLACE(description, ' or ', ' ou ') WHERE description LIKE '% or %';
UPDATE characters SET description = REPLACE(description, ' of ', ' de ') WHERE description LIKE '% of %';
UPDATE characters SET description = REPLACE(description, ' the ', ' o ') WHERE description LIKE '% the %';
COMMIT;